### ISSUE TITLE
Generated methods don't have Javadoc.

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#132]
_Migrated from Google Code (issue 59)_

**Comment by mirabilos** [comment]
It is **very** unfortunate that this was solved in v0.12.0 as it was, leading not only to https://github.com/rzwitserloot/lombok/issues/2443 but also to problems with IntelliJ as `@return` is not valid JavaDoc for a slot:

![Screenshot_20210113_010028](https://user-images.githubusercontent.com/861078/104389279-5efcf680-553b-11eb-9777-5780c324b442.png)

⚠ IntelliJ will **remove** them on “reindent file”!

I’d have preferred (or would love to have as an option) synthetic `@param`/`@return` values, with all the logic in the description, since it pretty much duplicates the description anyway.

**Comment by mirabilos** [comment]
Cross-linking https://youtrack.jetbrains.com/issue/IDEA-259347 for the IntelliJ issue
