### ISSUE TITLE
@setter    java.lang.String  trim()

### ISSUE THREAD

**Issue by SmileTower** [projectlombok/lombok#1720]
like this :
Can you provide such a method

StringUtils.trimToNull(null)          = null
StringUtils.trimToNull("")            = null
StringUtils.trimToNull("     ")       = null
StringUtils.trimToNull("abc")         = "abc"
StringUtils.trimToNull("    abc    ") = "abc"

org.apache.commons.lang3.StringUtils#trimToNull

public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
}

public void setUsername(String username) {
        this.username = StringUtils.trimToNull(username);
}

**Comment by grimly** [comment]
That's where more specific cases should be handled by yourself.

Myself I would prefer to use or just allow an empty string instead or even an optional of String. Why not even use the Option class from Vavr.

I hope you see my point. You have so much opinions in the java community it would be difficult or impossible to please everyone.

**Comment by voragoth** [comment]
Believe or not this is a common case, would be great have the option of trim the string in the @Data or @Setter.

**Comment by janmaterne** [comment]
If this is a "common case" is more an individual point of perspective imo.
Personally I can't remember to have seen this before.

And this would only work for String arguments.
Therefore I would suggest more a specialized annotation like @StringSetter which could handle more string specific behaviour.
@StringSetter(trim=true, convertion=uppercase|lowercase|none, maxLength=positiveNumber|unset)

- trim: trim a non null string (like you suggested)
- convertion: nonNullValue.toUpperCase(), nonNullValue.toLowerCase()
- maxLength: cut after the specified length or leave it as it is if not specified

**Comment by voragoth** [comment]
The @StringSetter option sounds amazing. About my point of view, you not always have the option to edit or optimize your data sources, and when the DB admin define the data as fixed char instead or varchar, and other similar cases, you need to do the setters at hand with the boilerplate code, or use reflections and the performance impoverishment of that. Your option make my life a lot easier.

**Comment by srbala** [comment]
May be having property for Setter (and @Data) like  `lombok.setter.trimString`, default false will support as is, activated true as needed

**Comment by voduku** [comment]
Hi, is this ticket lost?

**Comment by erizzo** [comment]
Ping...

**Comment by rzwitserloot** [comment]
That's not what null is for, this request is silly, it's not boilerplate. Will never happen. I apologize for not having closed it earlier.

**Comment by rdadbhawala** [comment]
The request is not silly. May be, it is not boilerplate, but it is a practical need in business applications which deal with user input, and the typical boilerplate code is the ideal place to handle it.

**Comment by erizzo** [comment]
> That's not what null is for, this request is silly, it's not boilerplate. Will never happen. I apologize for not having closed it earlier.

Given the quality of Lombok and the way the developers interact with the community in general, I'm quite surprised to see what looks like a totally dismissive attitude in this response. I can only hope that the feature request is misunderstood by @rzwitserloot which makes him think it's a "silly" request (and say something seemingly irrelevant like "that's not what null is for" which makes no sense at all to me).
I can try to re-word the request, since it's clear that people encounter this need and are forced to override setters to implement it, which defeats the convenience of using @Setter in the first place. Here goes:

Please provide an optional boolean property to the `@Setter` annotation that, when set to `true`, will include null-safe trimming of the passed-in value in the generated setter method when the field is of type `String`. A suggestion for the property name is `autoTrim` and the default value would be `false` (to maintain backwards compatibility).
When `autoTrim` is `true`, the generated setter method would look like this:
```java
public void setUsername(String name) {
    this.name = name == null ? null : name.trim();
}
```

As an alternative, a new annotation, suggested name `@StringSetter`, could be introduced that implements trimming (and potentially other String-specific options) in the generated setter(s).

**Comment by erizzo** [comment]
I'd be willing to explore contributing this enhancement if the project team was open to accepting a pull request.

**Comment by janrieke** [comment]
I don't think this proposition is a good idea, because:

1. Having an annotation parameter just for the case that it is present on method with a `String` parameter can be confusing. What do you do when it's `true` on a non-`String`? Error out? Ignore it? Furthermore, it clutters your auto-completion.
2. A special `@StringSetter` seems even more ridiculous to me. Where do we go from there? `@StringGetter`? `@IntegerSetter(maxValue=10, minValue=0)`? Even if we can agree that this will never happen, another annotation that does nearly the same than another annotation is a huge maintenance burden: You have think about all those possible interdependencies (e.g. with `@Data`).
3. What do you do with constructors? Should they also automatically trim once there such special setter? What about `@(Super)Builder`?
4. Last but (at least to me) most important: I barely see such a pattern in my daily coding life. I would even consider it bad practice in many cases, because you should _always_ sanitize (user) input as early as possible. Sanitizing in a data or value class is in most cases one step too late. If your data class happens to be the first step of your input pipeline (maybe because you are using a deserialization framework like Jackson), you should still make the sanitation explicit, because in such a case that's definitely not boilerplate.

**Comment by srbala** [comment]
Ideally, the uninitialized field is set to the default value needed. It can be in the Class definition level or a validation layer.

**Comment by elfwine** [comment]
I found out that whenever an old system application insert/update data to SQLServer DB, it added spaces to fill the digit of characters if data type is char. E.g., column data type is char(8) and the value is only 4 digit characters, it will add 4 spaces at the end. In new application, those Tables with data type char(d) are mapped as String in Entity classes. The idea of trimming a String field if it's not null is helpful in cases like this.
