### ISSUE TITLE
Lombok does not reflect refactoring changes to other classes in Eclipse

### ISSUE THREAD

**Issue by manueljordan** [projectlombok/lombok#1726]
Hello

For more details here:

* [STS does not apply expected refactoring with Lombok](https://github.com/spring-projects/spring-ide/issues/288)

If I have an entity class with `@Data` I can confirm the getter/setters and other (toString etc) are generated. I can use that POJO in peace in other classes. But if for example I have the `name` field and later is refactored to `firstName` the getter/setter are **only** reflected in the same class, but not in other classes.

**Comment by jdimeo** [comment]
This seems like a fundamental impossibility. If you refactor the field, then Lombok re-generates the getters and setters and to the rest of the world, it was a delete-then-add action (the old methods disappeared and then new ones appeared). You would have to do some really fancy and complicated tricks to anticipate what the new ones will be called, hook into Eclipse's refactoring engine, apply the refactor, then allow the methods to change.

Likewise, Eclipse can't refactor the methods themselves because it's generated. If Eclipse could refactor them, then a workaround would be to rename the methods via the outline view then rename the fields to match.

Not a member of the Lombok team, but I would rate this as "there are bigger fish to fry".

**Comment by Rawi01** [comment]
The issue has been addressed and is [covered by a test](https://github.com/projectlombok/lombok/blob/master/test/eclipse/src/lombok/eclipse/refactoring/RenameTest.java)
