### ISSUE TITLE
FieldNameConstants not working correctly

### ISSUE THREAD

**Issue by Streamline27** [projectlombok/lombok#1984]
The code like this:
```
@Builder
@FieldNameConstants
public class Example {
    public final String fieldNumberOne;
    public final String fieldNumberTwo;
}
```

Is delomboked to this:

```
@Builder
public class Example {
    public static final String nullFIELD_NUMBER_ONEnull = "fieldNumberOne";
    public static final String nullFIELD_NUMBER_TWOnull = "fieldNumberTwo";
    public final String fieldNumberOne;
    public final String fieldNumberTwo;
}
```

Lombok version: 1.18.4
Plugin version: 0.22.2017.3

**Comment by rspilker** [comment]
Could it be that you're using IntelliJ, because since 1.8.4 we no longer generate the constants in the camse type, but generate/use an inner type instead. See [the FieldNameConstants documentation](https://projectlombok.org/features/experimental/FieldNameConstants).

If it is an IntelliJ issue, please report it at [the Lombol IntelliJ Plugin issue tracker](https://github.com/mplushnikov/lombok-intellij-plugin/issues).

If it is not, please show the exact command you use to invoke delombok.
