### ISSUE TITLE
[FEATURE] Ability to get value from builder

### ISSUE THREAD

**Issue by JBodkin-LH** [projectlombok/lombok#2808]
**Describe the feature**
Add the ability to add getters on the automatically generated builder class via the configuration file or annotation

**Describe the target audience**
I'm working on a project that implements event sourcing. When generating the projection from the event stream, the logic has a state machine that looks at the previous fold-left value and the current value to determine the new value. As a workaround, the logic calls the build method to temporarily inspect the current state but this means that more objects will need to be garbage collected by the JVM and increases the complexity of the validation logic required in the constructor

**Comment by skaba** [comment]
Instead of a getter I would propose a setter that accepts a Function instead.

Lombok
```java
import lombok.Builder;

@Builder
public class Pojo {
    private String test;
}
````
Vanilla Java
```java
public class Pojo {
    private String test;

    @java.lang.SuppressWarnings("all")
    Pojo(final String test) {
        this.test = test;
    }


    @java.lang.SuppressWarnings("all")
    public static class PojoBuilder {
        @java.lang.SuppressWarnings("all")
        private String test;

        @java.lang.SuppressWarnings("all")
        PojoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Pojo.PojoBuilder test(final String test) {
            this.test = test;
            return this;
        }

       //Extra
       public Pojo.PojoBuilder test(final Function<String,String> test) {
            this.test = test.apply(this.test)
            return this;
        }

       //////////

        @java.lang.SuppressWarnings("all")
        public Pojo build() {
            return new Pojo(this.test);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Pojo.PojoBuilder(test=" + this.test + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Pojo.PojoBuilder builder() {
        return new Pojo.PojoBuilder();
    }
}

```

**Comment by wingsofovnia** [comment]
Having no getters also makes it impossible to use from Kotlin:
```java
@Value
@Builder(setterPrefix="set")
class MyClass {
  String text;
}
```
```kotlin
fun myClassWith(block: MyClass.MyClassBuilder.() -> Unit) = TODO("builder impl")
fun main() {
  myClassWith {
    text = "my text" // doesn't work because there is no getter -> isn't recognized as property
  }
}
```

I don't see any reason for not allowing Builder to be a valid POJO.

**Comment by rzwitserloot** [comment]
We're not adding this, sorry.

**Comment by HubFanBoy** [comment]
> We're not adding this, sorry.

OK, but what is the reason?

**Comment by burdoto** [comment]
also in dire need for this ... but kinda feel like theres not going to be a proper explanation for why not, because based on my previous issue reports have shown this project, while being a real life- and daysaver, is maintained with a very certain and very specific mindset - "i said no, bcs i dont wanna"

sorry for the kinda front, but this is a truly needed change, for various reasons - not just the reported kotlin issue.

edit: yes i saw the wall of text about "how and why this is out of scope" and "its too hard to make" - and yes i do think it has absolutely invalid reasoning and goes against the entire reason why i use lombok - to save time - this feature would save time, regardless of any kind of anti-pattern someone sees - i dont know whether you are aware of how often i'm being fronted for using lombok bcs its "abuse" and "lazy"
