### ISSUE TITLE
Generate object comparison implementation (implement Comparable<T>)

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#281]
_Migrated from Google Code (issue 208)_

**Comment by douglassparker** [comment]
I'm not sure why you think this would be difficult. The attributes of @CompareTo would be the same as for ``@EqualsAndHashCode.`` Use Apache Commons Lang CompareToBuilder to implement.
```Java
@CompareTo(callSuper=true,  include={"field1", "field2", "field3"}
class Foo {
}

//generates
class Foo implements Comparable<Foo> {
...
    public int compareTo(Foo foo) {
        return new CompareToBuilder()
              .appendSuper(super.compareTo(foo)
             .append(this.field1, foo.field1)
             .append(this.field2, myClass.field2)
             .append(this.field3, myClass.field3)
             .toComparison();
    }
}
```
Actually, it would have to be a little more complicated, because you would have to allow for sorting in descending order for each field. I agree that this should not be allowed unless all selected fields are themselves Comparable.  

It also might be nice to allow a custom comparator got complex cases, e.g,

```Java
@CompareTo(comparator=FooComparator.class)
```

This would be a very handy feature and I urge you to reconsider.

Kudos! Lombok is a fantastic framework.

**Comment by Maaartinus** [comment]
This issue is closed, but there's a newer discussion (but no progress) in #512.
