### ISSUE TITLE
[FEATURE] Replace @Accessors with new @FluentGetter, @FluentSetter, @FluentChainSetter, @ChainSetter

### ISSUE THREAD

**Issue by Cypher01** [projectlombok/lombok#2847]
The `@Accessors` annotation limits the configuration to have only one version of Getters and Setters, fluent or not fluent, chain or not chain. And one has to admit, it was never a good design to have a separate annotation to configure a different annotation.

### Improvement idea 1:
The 'fluent' and 'chain' configuations should be directly in `@Setter` and the 'fluent' configuation should be directly in `@Getter` ('chain' doesn't affect Getters). The 'prefix' configuration is out of scope of this feature request.

### Improvement idea 2 resp. feature request:
The scope of this feature request is to have the opportunity to have both, fluent _and_ not fluent Getters and Setters, as well as chained _and_ not chained Setters.

The probably cleanest solution would be to get rid of configuration parameters and switch to separate new annotations.

### Suggestion:
Remove
- `@Accessors`

Keep
- `@Getter`
- `@Setter`

Add new
- `@FluentGetter`
- `@FluentSetter`
- `@FluentChainSetter` (or `@FluentChainedSetter`)
- `@ChainSetter` (or `@ChainedSetter`)

There are limitations: `@Setter` and `@ChainSetter` would collide as they have the same signature and only different return types. The same goes for `@FluentSetter` and `@FluentChainSetter`. Not sure what would be the best solution for this.

### Alternative:
Remove
- `@Accessors`

Keep
- `@Getter`

Update
- `@Setter` -> Add boolean 'chain' configuration

Add new
- `@FluentGetter`
- `@FluentSetter` -> Also include boolean 'chain' configuration

### To give a little bit of context:
The idea comes from the OpenAPI generator. When generating API models, the generator adds three accessors:
- default Getter, like `public String getMyString()`
- default Setter, like `public void setMyString(String myString)`
- _additionally_ a fluent chained setter, like `public MyClass myString(String myString)`

With these changes users have the opportunity to add all different permutations of Getters and Setters to their classes. This would be a great improvement making old basic lombok functionality cleaner, easier to use, and overall better.

**Comment by almson** [comment]
Fluent accessors are used throughout the JDK and are good style. Please move `fluent` into `@Getter` to make using it more elegant.

Could the above idea of multiple getters be implemented by setting multiple @Getter annotations?

**Comment by rzwitserloot** [comment]
> And one has to admit, it was never a good design to have a separate annotation to configure a different annotation.

Actually, it is. I find this deplorable sentence insulting. I shall take no offense, as perhaps this is a cultural misunderstanding: "One has to admit"? You're not the queen of england. Who the heck is "One"? __You__ do not like it. That's fine. But own it! Don't couch your dislike in nebulous, confounding terminology. Did you mean 'you' do not like it? Did you mean the queen of england did not like it? Did you mean a nebulous, unnamed crowd does not like it? Did you mean that anybody can use objective reasoning to determine that this is bad API design?

It makes communication much more efficient when you just say precisely what you mean. I'm not insulted when you tear my API designs a new one (attack the product, not the person). I get a little miffed when you make nebulous, unfalsifiable claims that sound grander than they really are. "One has to admit" insinuates that many agree with the statement without actually pinning yourself to defending that particular hill. I don't like this.

I'll rephase what you meant:

> __I__ do not like this API design.

That's nice. I do, it's intentional, there are many reasons, I'm pretty sure you lack the context to understand many of them (but a waltz through the lombok commits will clarify things.

A very small selection of the many many reasons:

* Generating more than one setter is ridiculous. Fix the project: Something inside it is having duelling needs (e.g. you are using the same class both in a framework that demands the full beanspec treatment: "setters _must_ return `void` and _must_ have a `set` prefix" but, you also want/need fluent+chain setters for some reason. Fix that - adjust your style guides, as its obviously a bad idea to dictate via style guide that you want chain/fluent but then use a library that doesn't work with your style guide. Alternatively, fix the thing you are using that demands beanspec form setters).

We don't cater to non-boilerplate. Wanting both is sufficiently bizarre and exotic that we do not cater to this and don't want to. There are good reasons for this: If we lower the bar of 'what do we cater to', we inevitably end up in a place where you can use lombok to generate a combinatorial explosion of things, and we've grown lombok to hundreds of annotations or at least have grown most lombok features into having ten+ parameters. This negatively affects the learning curve and muddies the water about what is truly 'boilerplate' and is stuff you should probably doing, vs. weird stuff that caters to weird, exotic styles and needs. You might disagree with this mindset, but that's not relevant. This serves merely as explanation why this issue is being closed. It's not done on a whim.

* Fluent/chaining is designed to be something you configure at a higher level: For an entire package, source-set, project, or even workspace. Versus 'I just want a setter here', which obviously wouldn't be, you configure that per field/per class. Hence why there is no separate `@FluentSetter`.

* What do you actually want? `@FluentSetter`, `@FluentChainingSetter`, `@ChainingSetter`, `@PlainSetter`? You think that's an improvement? Really? If that's not what you wanted, surely you can see how what you want is simply 'I want an annotation for the exact style _I_ like'. The world is a little larger than you, though. Feature requests that boil down to "please enshrine my preferred style at the cost of others" are, obviously, denied. 

I've written these down as a favour to those looking for some sort of explanation. Not to start a debate. This issue is closed, and no debates about style preference or API design is going to change this. Room for further discussion is therefore limited; this isn't the place to hold a debate about API design and code style. Falsifiable, technical statements are acceptable. I cannot fathom any such arguments here, though.

**Comment by Cypher01** [comment]
Wow, I didn't expect such an extreme reaction. Maybe it is a cultural misunderstanding, or I simply didn't choose my words carefully enough, I'm not a native speaker. If you feel disrespected or insulted, I'm sorry. I did't want to be unpolite. But I still need to clarify some things.

> attack the product, not the person

I never attacked a person. Even if I wrote "I do not like this design" instead of "it was never a good design", I only talk about the design itself, not the person who did it. This accusation is unfounded.

> Generating more than one setter is ridiculous. Fix the project: Something inside it is having duelling needs

At the bottom of my initial comment I gave some context. The idea comes from the OpenAPI generator. The idea is to have the choice between two different setters. As you made clear, that you don't want to start a debate, let's not talk about if this is good or bad.

> setters _must_ return void and _must_ have a `set` prefix

Beanspec, fine, but if I don't overlook something, even without changing the design, this statement conflicts with the presence of the `@Accessors` annotation. So I don't understand why you point this out here. Again, no debate, just what I think.

Overall I can say, this Github issue was meant to be a feature request based on constructive criticism, not to insult anyone. I hope this is clear now.

**Comment by rzwitserloot** [comment]
> If you feel disrespected or insulted

I said I took no offense :)

> I never attacked a person.

I didn't mean to say that you did - you denigrated the API design but in a roundabout way. I was trying to _highlight_ that it was an attack on an idea and not a person, hence, no need to be so roundabout.

> The idea comes from the OpenAPI generator.

I have no idea why the OpenAPI generates 2 setters, but it seems rather daft to me to do this.

**Comment by almson** [comment]
@rzwitserloot I don't know how I feel about your insistence on making fluent/chain configurable only in a separate annotation (at a minimum, it bloats the API), but it would have definitely helped me if it was clearly documented. I've never used lombok config, and didn't realize it could be used as a project-wide style guide..
