### ISSUE TITLE
[FEATURE] ToString's onlyExplicitlyIncluded configurable from lombok.config

### ISSUE THREAD

**Issue by mickroll** [projectlombok/lombok#2849]
As there is the `@ToString(onlyExplicitlyIncluded = true/false)` option already, it would make sense to have the ability of setting it once across the project at the `lombok.config`, eg. via `lombok.toString.onlyExplicitlyIncluded = true/false`

Justification:
- Improved signal-to-noise ratio
- Better readability (arguably)
- Helps keeping project convention consistent
- would work similar to and alongside with `lombok.toString.doNotUseGetters`, `lombok.toString.includeFieldNames` and `lombok.toString.callSuper`

BTW. Thanks for adding this option. It really helps preventing data leakage into log files 👍

**Comment by rzwitserloot** [comment]
Fair enough. Barely got across the value vs. maintenance burden hurdle, but made it.

**Comment by mickroll** [comment]
@rzwitserloot Great 👍

**Comment by janrieke** [comment]
I just noticed that commit 6d2a474e55db3937eafa5a6d089efd5ba75a62bf that implemented this change breaks a lot of the tests. Didn't investigate further on the cause.

**Comment by mickroll** [comment]
So... maybe reopen this feature?

**Comment by rspilker** [comment]
@janrieke Any ideas on why this breaks so many tests? I haven't verified that statement myself.

**Comment by rspilker** [comment]
Yes, the reason is that this feature exposed a three year old bug, where we cast the default parameter to the wrong type, and the catch block then returns `false` for the `includeFieldNames`, which is one of the rare cases where the default of a boolean flag is `true` instead of `false`.

The proper solution is to fix the offending code, which we're doing right now, and to change the after-files for this specific feature, that should have included the field names.

**Comment by rzwitserloot** [comment]
Well, I checked this out, and I conclude that those tests do fail, and must have always failed. Except they didn't. :raise eyebrow:.

I, uh, fixed the impossible thingie, see commits 2685d37 and daee44d. I'm getting all greens across the board now, without reverting the commit.
