### ISSUE TITLE
Question about a comment

### ISSUE THREAD

**Issue by shaoyunli** [projectlombok/lombok#2942]
I am a bit confused with the comment in the function getOverrideFieldOffset() in /src/utils/lombok/permit/Permit.java line https://github.com/projectlombok/lombok/blob/5120abe4741c78d19d7e65404f407cfe57074a47/src/utils/lombok/permit/Permit.java#L44

// The below seems very risky, but for all AccessibleObjects in java today it does work, and starting with JDK12, making the field accessible is no longer possible.

Do you mean in the version with and after JDK12, the setAccessible function of AccessibleObject is no longer possbile? But what will happen to use this function with the version JDK12+?

**Comment by Rawi01** [comment]
Since Java 9 using `setAccessible` generates a warning if you try to access fields/methods of an non-exported class. As lombok needs to read/write java compiler classes it hides this warning by directly setting the field using `Unsafe`. Since Java 12 the used `override` field is internal and lombok uses a fake class to find the actual offset of the field. `setAccessible` still works properly if you access classes that allow you to do that.
