### ISSUE TITLE
Allow field name specification for @Log (and friends)

### ISSUE THREAD

**Issue by cjstehno** [projectlombok/lombok#2970]
It would be nice to have the logging annotations allow for the logging field name to be configured, something like:

```java
@Slf4j(name="LOGGER")
```

to generate something like:

```java
private static final Logger LOGGER = LoggerFactory.getLogger(YourClass.class);
```

I have some co-workers who are very adamant that a static field should be in all caps. It would also be helpful in situations where you may have more than one logger in a class.

**Comment by Rawi01** [comment]
You can change the field name by setting the `lombok.log.fieldName` config key in your [lombok.config](https://projectlombok.org/features/configuration).

**Comment by cjstehno** [comment]
That would work if you want ALL of them named the same thing. The approach I am suggesting would allow it to be configured on a per-use basis.

**Comment by Rawi01** [comment]
That's right, but why do you want to use different names in the same project/module? Are multiple loggers in the same class something you use often and do you think that this is still boilerplate? To be honest I have never seen that in one of my projects.

**Comment by rzwitserloot** [comment]
> That would work if you want ALL of them named the same thing. The approach I am suggesting would allow it to be configured on a per-use basis.

We made an intentional choice - that only the most exotic usecases would possibly by interested in configuring the name of the logger field on a per-class basis. We don't cater to those use-cases, because that road inevitably leads to the same place: 50+ options on each and every annotation we have, and a combinatorial explosion that is not testable. Not an acceptable situation, and surely you'd agree with that, if you think through what lombok would look like if you go down this rabbit hole.

The solution is painful but, IMO, the only right move: Grow up. It's ridiculous to do the styleguide fighting by way of who gets to a source file first. Have a conversation about it, pick a style, and try to be diplomatic about it. Give and take.

If you want some arguments, well, lombok does not default to `LOGGER`, that's one. Just about every doc out there says that all-caps is for 'constants'. "anything that is `static final`", that is one definition for "constant". But surely `static final List<String> list = new ArrayList<>();` doesn't count, right? You can add and remove stuff from that list at will, it's not immutable at all. Is that 'constant'? Clearly no. Loggers? That's... a slightly harder case to make, but it mostly doesn't swim, walk, or sound like a constant to me.

But, it's just some name. One could argue that logger statements should be particularly obvious, and caps help (funnily enough, one could _also_ argue that they should be _less_ obvious, which would be an excellent argument _against_ all-caps, so that's a bit of a two-edged sword). If the other folks on the team are considerably more invested in seeing it in all caps, then give in. Add the key to the proejct-global `lombok.config`. But if this turns into a situation where a chunk of the dev team takes the 'THIS.. IS... SPARTAAAAAA!!!!!' route on every mostly meaningless style 'debate', do yourself a favour. Find another team to work with.
