### ISSUE TITLE
[BUG] with @Log4j2, Eclipse fails to fully populate code completion suggestions

### ISSUE THREAD

**Issue by andi-huber** [projectlombok/lombok#2976]
Given

```java
@Log4j2
public class AnyClass {
    void action() {
        // log.  <-- trigger code completion
    }
}
```
_Eclipse_ (2021-09) fails to fully populate code completion suggestions, that is, in the above case it believes `log` to be of type `Object.class` and does not provide any methods specific to the `lombok.extern.log4j.Log4j2` type.

Lombok version https://github.com/projectlombok/lombok/commit/ba68962cec99cb1411ed7cac259301edc417ebc5

**Comment by rzwitserloot** [comment]
Adding some context:

I'm at a total loss for why this might be, and our testing infrastructure cannot easily deal with this case (in that e.g. `log.warn("hello")` would not actually cause an errors, the problem is in what we're doing to eclipse's intermediate view which the auto-completer uses, it 'corrects itself' at the end of the pipeline, and our test infra tests only the entire pipeline: Source file in, check the AST that comes out after lombok is done with it.

That means it'll probably be a rather involved and lengthy process to chase this one down, involving running an eclipse from eclipse so we can debug through it and hot-code-replace lombok in that eclipse. That or wait for eclipse boot a few hundred times. It's been a while since I did that :(

**Comment by andi-huber** [comment]
No worries, this is pretty low priority to me. Happy if you add this to the list of known issues and don't further investigate.

**Comment by Rawi01** [comment]
Hmm, I'm unable to reproduce this
![img](https://user-images.githubusercontent.com/5850477/135109545-d4a812e5-f0c7-433c-bee4-fb435efe8c67.png)

**Comment by andi-huber** [comment]
![image](https://user-images.githubusercontent.com/17565970/135493854-cf407ca6-3972-467c-bad1-891ecbe04463.png)
Referencing latest build from master on classpath:
![image](https://user-images.githubusercontent.com/17565970/135493967-a7bbd50e-1d6c-4f47-9aec-9e7dd42d0fca.png)

**Comment by andi-huber** [comment]
![image](https://user-images.githubusercontent.com/17565970/135494845-c0ad1f4d-b6d9-4ebf-8b88-5918ec74eaaa.png)

**Comment by andi-huber** [comment]
Well I double checked and found that on my end this example (no _lombok_ involved) does not work either:
```java
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class AnyClass {

    private static Logger log = LogManager.getLogger("");

    void action() {
        //log.  <-- trigger code completion
    }
}
```

Which strongly suggests, that the issue is not _lombok_ related. I'm closing this now.
Sorry for the noise.
