### ISSUE TITLE
can not format a String to LocalDateTime when the target object annotated with @Builder

### ISSUE THREAD

**Issue by aludashic9** [projectlombok/lombok#2979]
my code is here below

```
@PostMapping("user")
    public BaseResult insertUser(@RequestBody LoginUserVo user) {

        log.info("insert userVo: {}", user);
        return ArrayResult.success(Collections.singleton(user));
    }

@Data
@Builder
public class LoginUserVo {

    private Long id;

    private String name;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private LocalDateTime loginTime;
}
```

when i remote `@Builder` from `LoginUserVo`, it works

**Comment by rzwitserloot** [comment]
The `timezone` part of that `@JsonFormat` does not make any sense (you are rendering a timezone-less bit of information into another timezone-less bit of information. Why are you mentioning a timezone)?

That and in general the lack of detail on this bug report means I have no idea what the problem is and no idea how to fix it.

There is no stack trace. I have no idea what `@PostMapping` or `@JsonFormat` are (they are not in the core libraries; do not assume that every java programmer on the planet uses stuff that isn't in java.*).

Not enough detail to salvage this issue. Spend some time to write a complete self-contained test case with an actual description of what lombok does vs. what you wanted it to do, or if errors are involved, stack traces and error messages. If you can't produce a self contained test case, spend a lot of time describing exactly your environment and the libraries you are using along with the versions and such.

Lombok is open source. You're asking someone to do a ton of legwork to try to make sense of your bug report, for free. Open source is collaborative and as such it all works much better if everyone just does what they are best at. As you're running into this problem and familiar with the technologies you are using here, presumably you're the star of the show when it comes to writing a clear bug report :)

**Comment by janrieke** [comment]
This is probably also covered by https://stackoverflow.com/questions/51464720/lombok-1-18-0-and-jackson-2-9-6-not-working-together/51465038#51465038
