### ISSUE TITLE
Release Lombok for Java 17 on Maven Central

### ISSUE THREAD

**Issue by mandrean** [projectlombok/lombok#2987]
Hi,

Any timeline for when Lombok for Java 17 will be up on Maven Central?

Can't use the edge repo at work.

**Comment by rzwitserloot** [comment]
It was there about... 12 hours before you posted this issue :)

[Here it is](https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.22/).

Sites like mvnrepository and such aren't listing it yet. That's because they are slow. Nothing we can do about that. Just stick `1.18.22` in your maven def and it should just work, those don't do a search, they go straight for that URL.
