### ISSUE TITLE
[BUG] @Builder Incompatible Types when another Constructor exists

### ISSUE THREAD

**Issue by AndreBritoKD** [projectlombok/lombok#3046]
**Describe the bug**
When we have a constructor that has som type as a parameter and we define an instance variable with default value two things happen

1. Compile error saying those are incompatible types
2. I had one case that I had :
`@Builder.Default
private List<Foo> fooList = new ArrayList<>()`

and in a custom constructor it was null

**To Reproduce**
Have this arrangement :

```
@Builder
@Data
public class Teste {

  @Builder.Default
  private String bla = "the sum is:";

  public Teste(List<Integer> ints) {
    int sum = 0;
    for (Integer anInt : ints) {
      sum = sum + anInt;
    }
    bla = bla + sum;

  }

}
```

**Expected behavior**
To maintain the custom constructor and generate the needed constructor for builder. Possibly check existing constructors and parameters and variables types to see if they match

**Version info (please complete the following information):**
 - Lombok version 1.18.22
 - Intellij 2021.2.2 
 - openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

**Comment by Rawi01** [comment]
All these things are mentioned in the documentation. `@Builder` will only generate a constructor if you have not added one yourself, `@Data` only generates a constructor using required fields. To generate an additional constructor add `@AllArgsConstructor` to the class. The `@Builder.Default` fields are empty because lombok moves the initializer to a new method. There is an open feature request (#2340) to change that behaviour but that is not that simple.
