### ISSUE TITLE
[BUG] @EqualsAndHashCode with @org.eclipse.jdt.annotation.NonNullByDefault generates invalid annotations

### ISSUE THREAD

**Issue by hangrysergey** [projectlombok/lombok#3055]
**Describe the bug**
@EqualsAndHashCode is supposed to take into account lombok.addNullAnnotations configuration, however that doesn't work properly and results in 'org.eclipse.jdt.annotation.Nullable cannot be resolved to a type'

**To Reproduce**
Eclipse 2019-12 (4.14)
-javaagent:lombok-1.18.22.jar
Maven:
```
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.22</version>
			<scope>provided</scope>
		</dependency>	
		<dependency>
			<groupId>io.github.solf</groupId>
			<artifactId>extra2-epl</artifactId>
			<version>2.7.0</version>
		</dependency>

```
lombok.config
`lombok.addNullAnnotations=none`
(or anything else really)

```
@NonNullByDefault
@EqualsAndHashCode 
public class LombokFail
{

}

```

-> **org.eclipse.jdt.annotation.Nullable cannot be resolved to a type**

Commenting out @NonNullByDefault fixes the issue

I assume the key moment here is that annotations I use include org.eclipse.jdt.annotation.NonNullByDefault but at the same time javax.annotation.Nonnull (instead of Eclipse's one) and some kind of detection/generation goes haywire inside.

**Expected behavior**
Correct annotations should be placed and code should generate properly.

**Version info (please complete the following information):**
Eclipse 2019-12 (4.14)
-javaagent:lombok-1.18.22.jar

**Comment by JohnPaulTaylorII** [comment]
Your problem is simply that solf has embedded it's own version of the NonNullByDefault annotation, without including the other Eclipse annotations. You need to declare the following dependency if you want to be able to resolve those annotations:

```
<dependency>
	<groupId>org.eclipse.jdt</groupId>
	<artifactId>org.eclipse.jdt.annotation</artifactId>
	<version>2.2.600</version>
</dependency>

```

**Comment by JohnPaulTaylorII** [comment]
I would assume that, when Lombok sees NonNullByDefault, it assumes (and rightly so) that you have all the Eclipse annotations on the classpath, not just NonNullByDefault. I think the heart of the issue is that the referenced solf library includes a half implementation of the Eclipse annotations, which essentially means that Lombok can only provide half a solution, and the compiler will complain about the missing half.

**Comment by hangrysergey** [comment]
I disagree that Lombok should assume anything.
There's configuration option 'lombok.addNullAnnotations' which is supposed to take care of resolving what annotations to use (including the option to use custom annotations).

I think it's a bug that Lombok 'decides' to use Eclipse's annotations disregarding the value of 'lombok.addNullAnnotations'

**Comment by JohnPaulTaylorII** [comment]
I believe what you're asking for is an impossible situation. You've specified the class as NonNullByDefault. This means that the argument to .equals(Object) is NonNull. However, this isn't true; .equals accepts null arguments. So Lombok _must_ mark the argument as nullable. The only correct annotation for this, since org.eclipse.jdt.annotation.NonNullByDefault was used, is org.eclipse.jdt.annotation.Nullable, so that is what Lombok must add to generate a correct .equals(Object) method. Otherwise, the method signature is incorrect and callers of .equals will be unable to compare to null.

It doesn't strike me as a bug that Lombok cannot respect a setting saying not to use null annotations when null annotations are already present in the code. Especially when the only valid solution is to make use of an annotation from the same source package. Again, the solf.nullanno package directly includes the code for one of the annotations from org.eclipse.jdt.annotation instead of correctly depending on the full (and very small) maven package.

**Comment by rzwitserloot** [comment]
Good work by everybody else who commented here – it is indeed intentional behaviour. The presence of NonNullByDefault means that `Nullable` must be added to e.g. `equals(@Nullable object other)`.

What you're asking is that lombok generates __broken code__. I get that it's confusing when you specifically asked lombok not to generate nullity annotations and it does so anyway, but it's intentional, correct, and will not be changed.
