### ISSUE TITLE
关于lombok重写equals方法的疑问

### ISSUE THREAD

**Issue by hkall** [projectlombok/lombok#3061]
你好，刚刚看了一下重写equals方法的代码

```
public boolean equals(final Object o) {
        if (o == this) {
            return true;
        } else if (!(o instanceof TestLombok)) {
            return false;
        } else {
            TestLombok other = (TestLombok)o;
            if (!other.canEqual(this)) {
                return false;
            } else {
                Object this$handOverTime = this.getHandOverTime();
                Object other$handOverTime = other.getHandOverTime();
                if (this$handOverTime == null) {
                    if (other$handOverTime != null) {
                        return false;
                    }
                } else if (!this$handOverTime.equals(other$handOverTime)) {
                    return false;
                }

                Object this$handoverTime = this.getHandOverTime();
                Object other$handoverTime = other.getHandOverTime();
                if (this$handoverTime == null) {
                    if (other$handoverTime != null) {
                        return false;
                    }
                } else if (!this$handoverTime.equals(other$handoverTime)) {
                    return false;
                }

                return true;
            }
        }
    }

    protected boolean canEqual(final Object other) {
        return other instanceof TestLombok;
    }
```
 这里equals方法中两次判断  o instanceof TestLombok 是不是第一次主要是判断此对象是否为类本身或者子类的实例对象，下面是判断此对象是否为类本身的对象？还是说存在重复判断？请有空解答，谢谢！

**Comment by rspilker** [comment]
The test `(!(o instanceof TestLombok))` is to ensure that `o` is either an instance of the TestLombok class OR of a subclass. If that's not the case, the objects can never be equal.

If `o` is an instance of TestLombok or of a subclass, it is still uncertain if the class hierarchy fully supports the equals contract.

That's why we ask "other" is they "canEqual" us. And of you would call the reverse `a.equals(b)` to `b.equals(a)`, in all circumstances should that give you the same results.

And our default implementation of canEqual, which can be overwritten, is another instance-of check.

I hope this answers your question.

**Comment by rspilker** [comment]
If your class is final, we generate a different equals implementation.

**Comment by hkall** [comment]
> The test `(!(o instanceof TestLombok))` is to ensure that `o` is either an instance of the TestLombok class OR of a subclass. If that's not the case, the objects can never be equal.
> 
> If `o` is an instance of TestLombok or of a subclass, it is still uncertain if the class hierarchy fully supports the equals contract.
> 
> That's why we ask "other" is they "canEqual" us. And of you would call the reverse `a.equals(b)` to `b.equals(a)`, in all circumstances should that give you the same results.
> 
> And our default implementation of canEqual, which can be overwritten, is another instance-of check.
> 
> I hope this answers your question.

Thank you very much for your answer, which is very helpful to my understanding.
