### ISSUE TITLE
[FEATURE] Method chaining

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [projectlombok/lombok#3071]
**Describing the feature**
Annotation, that let methods return this instead of void. Target on methods or class.

Feature on methods:

```java
class Lomboked {
    public static void main() {
        new MethodChainingExample().setField1(0).setField2("fiel2").setProperty("key1", "value1").setProperty("key2", "value2");
    }
}

class MethodChainingExample {
    @Setter(onMethod_ = @MethodChaining)
    private int field1;

    @Setter(onMethod_ = @MethodChaining)
    private String field2;

    private Properties properties = new Properties();

    @MethodChaining
    public void setProperty(String key, String value) {
        properties.setProperty(key, value);
    }
}
```

Feature on class:

```java
class Lomboked {
    public static void main() {
        new MethodChainingExample().setField1(0).setField2("fiel2").setProperty("key1", "value1").setProperty("key2", "value2");
    }
}

@MethodChaining
class MethodChainingExample {
    @Setter
    private int field1;

    @Setter
    private String field2;

    private Properties properties = new Properties();

    public void setProperty(String key, String value) {
        properties.setProperty(key, value);
    }
}
```

Existing Lombok feature:

```java
class ExistingLombokFeature {
    public static void main() {
        new MethodChainingExample().setField1(0).setField2("fiel2").setProperty("key1", "value1").setProperty("key2", "value2");
    }
}

@Accessors(chain = true)
class MethodChainingExample {
    @Setter
    private int field1;

    @Setter
    private String field2;

    private Properties properties = new Properties();

    public MethodChainingExample setProperty(String key, String value) {
        try {
            properties.setProperty(key, value);
        } finally {
            return this;
        }
    }
}
```

Without Lombok:

```java
class WithoutLombok {
    public static void main() {
        new MethodChainingExample().setField1(0).setField2("fiel2").setProperty("key1", "value1").setProperty("key2", "value2");
    }
}

class MethodChainingExample {
    private int field1;

    private String field2;

    private Properties properties = new Properties();

    public MethodChainingExample setProperty(String key, String value) {
       try {
            properties.setProperty(key, value);
        } finally {
            return this;
        }
    }

    public MethodChainingExample setField1(int field1) {
        try {
            this.field1 = field1;
        } finally {
            return this;
        }
    }

    public MethodChainingExample setField2(String field2) {
        try {
            this.field2 = field2;
        } finally {
            return this;
        }
    }
}
```

**The target audience**
Any kinds of programs.

**Comment by juriad** [comment]
There already exists an annotation [`@This` by Checkerframework](https://checkerframework.org/api/org/checkerframework/common/returnsreceiver/qual/This.html), maybe Lombok could integrate with it.

It would work on any explicit or generated method
* that either has return type `void`,
* or the declared return type is a supertype of the current class

If the annotation is `lombok.This`, it is removed during compilation/delomboking. If it is from a different library (checkframwork), it is retained. How it should work on types is unclear to me - maybe just affect the generated methods where possible.

I can see a problem with just adding `return this` to the end - such instruction may not be reachable due to previous explicit returns. That would be solvable by wrapping the whole method in `try { ... } finally { return this; }` - or we could just let the compilation fail and urge the user to handle this manually.

I recently came across Concurnas and its [call-site double dot notation](https://concurnas.com/docs/functions.html#calling-functions-and-methods) for returning the receiver. But that looks out-of-scope for Lombok.

```java
class A {
  @This
  void do() {}
  
  @This
  A make() {}
}

class B {
  @This
  @Override
  void do() {}
  
  @This
  @Override
  A make() {}
}
```

Delomboked:
```java
class A {
  @This
  A do() {return this;}
  
  @This
  A make() {return this;}
}

class B {
  @This
  @Override
  B do() {return this;}
  
  @This
  @Override
  B make() {return this;}
}
```

**Comment by ValeryVerkhoturov** [comment]
@juriad 
If annotation with method in super class, it could be overriden, invoked with returning super type, casted to current type and returned current type.

Annotation could not be compared with another library, where it is implemented with retaining.

Breaking a chain can be an option in lombok.config.

**Comment by rspilker** [comment]
> I recently came across Concurnas and its call-site double dot notation for returning the receiver. But that looks out-of-scope for Lombok.

Dart had the same syntax. In Lombok, we cannot add that, since we can only use valid java syntax. The best we could do is 

```java
foo.$.setX(x).$.setY(y);
```

In this example I used `$`, but that could be anything other valid java identifier.

I would love to add a call site solution, since it also would work for other existing void-returning methods. However, how would you opt-in for this in your source file. What I mean by that is that most lombok features are triggered by adding an annotation on your source code at some level, so anyone reading your code understands that there might be something going on.

**Comment by rzwitserloot** [comment]
Nope, vetoed. I see only 3 routes to accomplish this, and they all suck too much.

## Option 1: Be like existing APIs.

What I mean is: Have a way to make lombok 'fix up' your methods, turning them from methods that have a declared return type of `void` into one that declares its own type as return type, and fixing/adding `return this;` statements to match it.

__This does not actually work out the way you want it to, it doesn't really make the method chainable__.

The real problem is hierarchy. The thing that messes this up is inheritance:

```java
class Parent {
  @Chainable
  public void whatever() {}
}

class Child extends Parent {}
```

would delombok to:

```java
class Parent {
  public Parent whatever() {
    return this;
  }
}

class Child extends Parent {}
```

and that is __wrong__. It should have delomboked to:

```java
class Child extends Parent {}
  @Override public Child whatever() {
    super.whatever();
    return this;
  }
}
```

But this has problems that make this well out of scope for reasonable feature requests:

* This just flat out breaks to bits if you work on separate compilation, i.e. if `Parent` and `Child` are not in the same project.
* Either code that has no lombok in it at all silently gets code injected if lombok is present, which is a bridge we will not cross, or, this doesn't happen unless you remember to write some annotation in `Child` to indicate: "Fix up" all inherited chainable methods please. Regardless of which one of these 2 nasty choices you make, you need resolution to deliver it, which means it's a highly complex feature with a large maintenance burden. Not worth it, surely.
* None of the above, and `@Chainable` is documented to do the wrong thing when you inherit classes.

All 3 options are such a massive downside that it kills the feature: It means the request is falls _far_ short of the benefit vs. cost ratio we need to accept it. Hence, this is __not acceptable__. We'll deny a PR that adds this feature in this exact fashion.

## Option 2: Generics hackery

There is a resolution-free, single-file way to solve it:

```java
class Parent<P extends Parent<P>> {
  @SuppressWarnings("unchecked")
  protected P self() {
    return (P) this;
  }

  // This was annotated @Chainable
  public P iAmChainable() {
    /* code from the so-marked method */
    return self(); // lombok-generated addition
  }
}
```

But, this means we need to make generics appear where currently there are none, and while the `self()` method is fine with me (it's `protected`, technically part of your public API, but only barely so), that generics is there for all to see and it's clearly not worth the cost of the convenience of being able to chain methods.

Also, taking existing APIs that return `void` and 'updating' them with `@Chainable` would be backwards incompatible. If OpenJDK project had suggested this feature and wrote up that the update'd be backwards incompatible I'd be writing rather vehement opposition to the plan, and we should hold ourselves to the same standard.

For these reasons, generics hackery is also __vetoed__ - we won't accept a PR that delivers the feature in this fashion

## Option 3: Our own syntax

What if instead of doing it 'call site' (on the methods that you want chainable), that instead you do it use-site: We invent new syntax that you can use to call any method, but to have the call resolve to the receiver, and of course for the invoke to be typed the same as the receiver - what double dot does in e.g. dart. As @rspilker said, lombok currently adheres to the rule that your java file must be syntactically valid (allowed to be non-sensical, i.e. semantically broken, but must syntactically pass), __before__ lombok runs. We can't break this rule unless we change how lombok works in javac - annotation processors don't get called unless syntax passes, so we'd have to rewrite it all to be agent/plugin based. It's an option, but that makes this an extremely drastic feature request.

So, eliminating the 'completely rewrite how lombok works in javac' option, it needs to syntactically pass, which gets us to Roel's syntax: `foo.setX(x).$.setY(y);`, where `.$.` is like a 'one step back please' - the thing before it is a method invoke (can even be to `void`), and I want the recipient, ignore the result of the method immediately before this.

However, this looks too vague: A java programmer that doesn't know about this lombok feature will be __completely__ lost, and to make matters worse, there is no lombok import nor can we make it so that syntactically the `.$.` node 'resolves' to a lombok-related thing. What I mean by that is, even if lombok isn't being run at all, if you have this file:

```java
import lombok.Getter;

public class Foo {
  @Getter String x;
}
```

and you as a java programmer look at it and go: What the heck is this?? - Then just follow the `@Getter` to where it lives (`lombok.Getter`, the class), and read its javadoc. You can't do that with the `.$.` node, which means it _must_ feel natural to the majority of java coders that ever see it, or we're asking a _heck_ of a lot.

Too much, as it turns out. This is beyond boilerplate fixing and too far into bending java into a completely different language.

As a general rule, if we deliver on a new language feature in a way that is clearly significantly inferior to what team OpenJDK could deliver on by just adding something to the language, then we shouldn't add it to lombok. Hence, this 3rd option also __vetoed__.

## I'm out of ideas

I see no other route to deliver on this. That's what it would take: Somebody to come up with something I'm not thinking of right now.

I'm closing this - if someone does have a great idea, post here and we'll re-open if that sounds like a winner.

**Comment by rspilker** [comment]
I totally agree with @rzwitserloot, but in all fairness we could implement it that lombok only processes `.$.` if you `import lombok.$;`.
