### ISSUE TITLE
[FEATURE] replace Beanutil.copyproperties() function

### ISSUE THREAD

**Issue by zundaren** [projectlombok/lombok#3077]
`Beanutil.copyproperties()` is a commonly used property copy, can we add a conversion annotation to replace it, for example: `@Convert(value=UserVO.class)`, The `getUserVO()` method is automatically generated at compile, This will improve coding efficiency.

```java
@Data                                                              
@Convert(UserVO.class)                                  
public class User {                                             
    private String name = "xxx";                          
    private Long age = 18L;                                 
}     

@Data
@Convert(User.class)
public class UserVO {
    private String name;
    private String age;
}
                                                          

//    public UserVO getUserVO() {
//        UserVO userVO = new UserVO();
//        userVO.setName(this.name);
//        userVO.setAge(this.age.toString());
//        return userVO;
//    }


   public static void main(String[] args) {
        User user = new User();
        user.setName("dv");
        user.setAge(15L);
        UserVO userVO = user.getUserVO();
        System.out.println(user.getName() + " | " + user.getAge());
    }
```

**Comment by juriad** [comment]
Other code-generating libraries can do this and do it better. Look at https://mapstruct.org/.

Lombok can't do this because the code requires the knowledge of the fields (and constructor and setters) of the target of the conversion - magic word - resolution.

It is also arguably the wrong place to do this in a data class because it mixes responsibilities - data class should hold data, not convert them. Once Lombok allows simple copying of properties of compatible types, there will come requests for adjusting the data types, using different constructors (mapping @Value), ignoring fields, deep copying of collections...

I am not a Lombok maintainer, but I expect this feature request to be closed for the aforementioned reasons.
