### ISSUE TITLE
[BUG] @Slf4j not working in java17

### ISSUE THREAD

**Issue by KaseiHaku** [projectlombok/lombok#3098]
**Describe the bug**
compile with maven, 
when module-info.java exist, fail with "cannot find symbol"
else success

**To Reproduce**

**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version: 1.18.22
 - Platform: idea, maven 3.8.4

**Additional context**
maven-compiler-plugin.version = 3.9.0
maven-compiler-plugin.configuration.release = 17

**Comment by rzwitserloot** [comment]
This will need some more details for us to accept it as a bug report. It sounds like you're saying: Just compile any `module-info.java` with jdk17 when lombok is on the classpath as you compile, even if you don't use any lombok stuff, and it fails. That sounds.. extraordinary, but if really true it should be trivial to write a test case.

Paste a self contained example (Sounds like you need 2 to 3 files: `pom.xml`, `module-info.java`, and possibly `Foobar.java` - a single actual source file in addition to the module file to e.g. use lombok or otherwise cause compilation to fail). Paste __all 3__ files, or a zip, so that one can just place them in a fresh folder, run `mvn compile` or whatnot on a system with the relevant versions of maven and openjdk installed, and see the error.

I'll re-open this issue once the reproduction is provided by somebody.

**Comment by domainy** [comment]
@rzwitserloot I have created a demo for this issue using gradle and spring boot project from start.spring.io. Here is the repo - https://github.com/domainy/spring-lombok-issue

**Comment by janrieke** [comment]
Lombok does not support Kotlin. I doubt that your example has anything to do with this issue.
