### ISSUE TITLE
With with onMethod not compiled[BUG] 

### ISSUE THREAD

**Issue by ytanikin** [projectlombok/lombok#3104]
**Describe the bug**
With with onMethod displays message during the compile, 
BillingAddress.java:12: error: 'onMethod' is not supported for @With on a type.

**To Reproduce**
```build.gradle settings    
compileOnly(
            "org.projectlombok:lombok:1.18.22"
    )

    annotationProcessor(
            "org.projectlombok:lombok:1.18.22"
    )
```
```@With(onMethod_ = @NotNull)
@AllArgsConstructor(staticName = "of")
public class BillingAddress {
    String address;
}
```
Java version is 11.
It works without onMethod param, I have tried as well with the old fashin way to declare onMethod annotation with @__NotNull. It doen't work with any other annotations(annotations I put after onMethod_) on With.
In Intellije IDEA it doesn't display the error, but when compile it gives me error. IDEA and the plugin versions are the latest.

**Expected behavior**
Compiles, and add annotation on generate methods

**Version info (please complete the following information):**
 - Lombok version 1.18.22, plutgin bundled 213.6461.79
 - Platform IDEA 2021.3.1

**Comment by rzwitserloot** [comment]
That's intentional - you're asking us to take a single annotation and to duplicate it for all those withers, which we won't currently do.

If your intent is to plaster `@NonNull` annotations everywhere, in the sense of 'this should not be null' (vs, perhaps, 'when making a CREATE TABLE statement, add a non-null constraint', for example), then this isn't the way. Set your package/class up with `@NonNullByDefault` or similar.

**Comment by ytanikin** [comment]
I have a problem with another annotation `@DynamoDBIgnore`. but why do you have `onMethod` parameter in `@With`?
