### ISSUE TITLE
[FEATURE] Package Level, Inheritance, Custom Annotation support for @ExtensionMethod

### ISSUE THREAD

**Issue by leopripos** [projectlombok/lombok#3124]
I come from C#, so `@ExtensionMethod` for java is an interesting feature for me. 
And for clarification, I'm not an expert of java, so correct me if I'm wrong since maybe I'm taking something that conflict with java best practice or something can not be implemented in java.

My thought is the reason of writing extensions is like writing a library or reuseable methods which will be use by others or ourself.
And it helps people to discover features (methods) using OO paradigm.

So I'm thinking about how to use `@ExtensionMethod` base on the idea above:
1. If I import specific package, it will enable the extension method
2. If I inherit specific class, it will enable the extension method
3. If I create custom annotation which has `@ExtensionMethod` annotation, it will enable extension methods where I use the custom annotation.
4. If I add the `@ExtensionMethod` to a class,  it will enable the extension method (CURRENTLY SUPPORTED)

So for example, here the extension class and I publish it to maven repository:
```java
package myproject.extensions;

public class StringExtensions {
       public static String processString(String value){ 
              // Do something here
              return null;
       }
}

public class ValidatorExtensions {
       public static IValidatorBuilder processValidator(IValidatorBuilder value){ 
              // Do something here
              return null;
       }
}

```
## Use Case 1: If I import specific package, it will enable the extension method ##
Here my code:
```java
@EnableExtensionMethod({myproject.extensions.StringExtensions.class})
package myproject.extensions;

```
When people using my package
```java
package otherproject

import myproject.extensions.*;

// Here he can use String.processString()
// Because this package import myproject.extensions.* package
```

## Use Case 2: If I inherit specific class, it will enable the extension method ##
Here my code:
```java
package myproject.extensions;

@EnableExtensionMethodWithIheritance({myproject.extensions.ValidatorExtensions.class})
public abstract class AbstractValidator {
   
}
```

When people using my package
```java
package otherproject;

import myproject.extensions;

public class RequestValidator extends AbstractValidator {
     public AbstractValidator() {
            // Here he can use IValidatorBuilder.processValidator()
            // because this class extends AbstractValidator
     }
}
```

## Use case 3: If I create custom annotation which has @ExtensionMethod annotation ##
Here my code:
```java
@EnableExtensionsMethod({myproject.extensions.ValidatorExtensions.class})
@EnableExtensionsMethod({myproject.extensions.StringExtensions.class})
public @interface FeatureNameExtension {
}
```

When people using my package
```java
@FeatureNameExtension
public abstract class SomeClass {
      // Here we can use IValidatorBuilder.processValidator()
      // Here he can use String.processString()
      // because of @FeatureNameExtension
}
```

and some small thought, at least for me, the `@ExtensionsMethod` naming a bit confusing
based on how it is used now, it should be: `@UseExtensionsMethod` or `@EnableExtensionMethod`

Thanks

**Comment by rzwitserloot** [comment]
> And it helps people to discover features (methods) using OO paradigm.

That's a very tricky statement. The fact that you get to write e.g. `somePathObject.writeString("hello");` isn't OO at all, it's just simple syntax sugar to remap that to `Files.writeString(somePathObject, "hello")`  – it's not object oriented, you can't 'override it' in the normal sense. It just _looks_ like OO. It's already a tricky case that leads to confusion, it's a very bad idea to start throwing the very terminology at the concept that only deepens that confusion.

> If I import specific package, it will enable the extension method

That won't work - `import x.y.z;` is java-ese for __alias__. An import statement runs absolutely nothing in `x.y.z`, it doesn't even cause x.y.z to load. An import statement __disappears__ during compilation, it isn't in the resulting class file at all. An import statement in java does ONLY two things:

* Any usage of `z` on its own anywhere a type is expected, is understood to be `x.y.z`. It saves some typing, that is all.
* If `x.y.z` is not on the classpath when you compile the code, javac will emit an error even if you use `z` nowhere. It doesn't have to do this; the spec merely indicates it will (and it does). It's effectively a 'linting' rule, if you simply delete the block of code in `javac` that generates this error, nothing would break. Other than this linting rule that the java lang spec says must be applied.

Hence, it'd be weird if all of a sudden if lombok is involved, an import _does_ have actual side effects. So, no, we're not going to do that.

> If I inherit specific class, it will enable the extension method

Also no. For a different reason: We don't 'like' lombok voodoo. We want somebody looking at java source code that uses lombok features to have a reasonable chance of figuring out what's happening even if they aren't aware lombok exists. When you see:

```java
@Value class Foo {
  String x;
}
```

Then:

* That `@Value` is a _direct link_ to the functionality lombok is going to apply (it turns the class into a value class), in contast to e.g. `extends SomethingUtterlyUnrelated` - where `SomethingUtterlyUnrelated` would add extension functionality. That's not obvious.
* `Value` is a lombok type, you can CMD+click it in your IDE or just hover over it for lombok's javadoc which will tell you precisely what's happening and indicates precisely which library is doing the work here.

If you need to go check the javadoc of seemingly unrelated sources in order to figure out that lombok is somehow involved, that's not good. There is SOME argument to be made that annotations can be considered to be inheritable (some are, some aren't), but lombok isn't really an annotation processor. It is a boilerplate buster: It's just that most of its features are triggered by using annotations. Hence, we don't want to go down that rabbit hole, and lombok holds as general principle that _all_ of its annotations (except `@NonNull`, because why not) are 'private' implementation details and therefore by definition cannot be considered to be inherited.

> If I create custom annotation which has @ExtensionMethod annotation, it will enable extension methods where I use the custom annotation.

This is a concept we call meta-annotations. You make an annotation of your own which implies a whole boatload of lombok annotations. It's a way to boilerplate-bust the boilerplate buster: If you want to stick:

```java
@ExtensionMethod({a.class, b.class})
@Value
@ToString(includeFieldNames = true)
@Accessors(fluent = true)
...
```

On multiple classes, just write one annotation that implies all that and stick _that_ annotation on your classes instead. One of our lead contributors is currently working on this. In order to fight the voodoo magic aspects, we'll probably __require__ that this annotation's fully qualified name includes `lombok` or `Lombok`. Thus, `com.foo.myproject.LombokDbModel` or `com.foo.myproject.lombokmeta.DbModel` - but something so that there's a fair shot that someone reading that code will figure out what's happening sooner rather than later.
