### ISSUE TITLE
[FEATURE] JDK 18 support

### ISSUE THREAD

**Issue by Rawi01** [projectlombok/lombok#3129]
Release date for Java 18 is 2022-03-22.

**Comment by rzwitserloot** [comment]
Did some testing with JDK18. All seems well (And build was updated; the targeted JDK versions are now 8/11/17/18 when you run the tests from the command line with ant. In addition, firing up eclipse itself using JDK18 as its own JVM also seems fine, and I do see a bunch of reports from time to time that this doesn't work; I assume those reports are from older versions where we use different (now broken due to OpenJDK's backwards incompatible romp through the securitymanager/reflection systems) hooks.

I'm waiting on roel to finish WithBy docs or sign off on moving that down the road, then it's time for a new release.
