### ISSUE TITLE
[BUG] NonNull does not check nulls for method returns

### ISSUE THREAD

**Issue by kennethjor** [projectlombok/lombok#3154]
**Describe the bug**
Annotating a method with `@NonNull` as below does not generate any non-null checking. See [test repo](https://github.com/kennethjor/lombok-nonnull-test/blob/main/src/test/java/NonNullTest.java) and [test run](https://github.com/kennethjor/lombok-nonnull-test/runs/5732188501).

```
@NonNull
public String nonnullReturn(String in) {
    return in;
}
```

**To Reproduce**
See test repo above.

**Expected behavior**
A null-check is added to the return variable.

**Version info (please complete the following information):**
 - Lombok version 1.18.22
 - Platform: Gradle and Lombok plugin.

**Comment by kennethjor** [comment]
I just saw on the small print on the docs that this serves a documentary role. Apologies, RTFM.

In that case, perhaps this should be a feature request or is there a specific reason this isn't a good idea?

**Comment by rzwitserloot** [comment]
It's not a good idea. For two reasons. They're both really esoteric reasons. At a glance I understand that you thought it would generate nullchecks on the way out (I have regrets about having lombok's `@NonNull` do double duty as documentary element. If I could go back in time and it were up to me, I'd undo it. I think I was the one advocating for its documentary second purpose and @rspilker was far less on board with the idea, so I do apologize for this). It's already documented and it would be effectively backwards incompatible if lombok starts emitting warnings for any `@NonNull` use outside of method parameters at this point, unfortunately.

Given that it's not obvious that it's a bad idea, I best explain in some detail!

## Locality

The author of method X cannot be considered to be completely in control of all code that calls X. Perhaps one can make the argument that if method X is private, that the author _is_, but any project that isn't trivial in total size effectively has no single author that fully beholds every line of code, every behaviour - even one-person projects, as you can't hold that much in your head.

Hence, runtime nullchecking to verify contract stipulations (and non-nullity is one such stipulation), even for private/package-private/non-exported methods is a plausible and sensible thing to want to do.

On the other hand, checking that _your_ code doesn't return null isn't anything like that. The entire method ought to be fully beholden in your head as you write it, or as you edit it. Perhaps it's a giant monstrosity and this is impossible, but that's rare - as a principle such methods should not exist. Lombok, by design, does not cater to boilerplate that simply doesn't come up unless you write really bad code: We assume that a lombok feature's mere existence lightly suggests it would be useful - and thus would be championing bad code style, which we don't want on our conscience.

Instead what you may want is to runtime-nullcheck the return value of __methods you call__, just to double check that _their_ contractual stipulation promise is true. However, there is no easy enough way to introduce it, and more generally if everybody aggressively nullchecks all the things, at some point 90% of every statement your JVM is running is the 15th superfluous nullcheck in a row and that's a bit daft. Lombok (and the JVM community at large) has standardized on either not null checking at all, or nullchecking arguments (and not nullchecking returned values), so let's stick with that.

## Nullity is more complex than that.

There are various nullity annotation frameworks out there. The problem is, what does it _mean_?

Given:

```
void foo(@NonNull String x) {}
```

There are 2 ways to read that. You (and 99% of the people I explain this to) think that these 2 different ways are a distinction without a difference:

* This method takes 1 parameter. The type of this parameter is `@NonNull String` - that is a type that can only be string. In contrast to `@Nullable String`, which is an 'OR' type: That is a type that indicates the value can either be an instance of String, or an instance of null (i.e. `null`).
* This method takes 1 parameter. The type of this parameter is `String`. In addition, it must not be `null`.

The problem is, whilst folks think that's practically speaking identical, it's not true at all. __Those two things are each other's opposite!__.

That first one should mean that if you nullcheck the argument, it should be a compiler error!

After all, this:

```
String y = whatever;
if (y instanceof Integer) {}
```

Is a compiler error. `y` cannot possibly be an instanceof Integer, so why write that code? On the flipside, if the annotation indicates a contractual stipulation (the meaning as in the second bullet point), then it should probably be a compilation warning if you _don't_ nullcheck it.

This is a real problem - if you turn on IDE nullity annotation compile-time checking, you run into this. That checker starts generating a boatload of warnings that you're injecting pointless nullchecks. They're getting a little better but mostly by reducing the amount of warnings they spit out, and 'finding weird code' __is their job__.

The point isn't that lombok should wash its hands and walk away from any and all nullity stuff. It merely means we need to be judicious with what we do support, and if we generate anything, to generate 'patterns' that are in widespread use. After all, an annotation based nullity compiler plugin either understands widespread use and acts accordingly, or are silly toys nobody uses. Either way, not our problem.

**Comment by kennethjor** [comment]
Thank you for your detailed response. After creating the issue, I did think to myself that I have never seen any code anywhere which checks for nulls before returning, so why would Lombok do it. To be honest, I just initially expected it for consistency, which is the first point your make about the dual purpose of the annotation. Hopefully, this will serve as further explanation, should anyone else have the same idea.

**Comment by Yith1** [comment]
Would it be possible to add a config option where the use of @NonNull in this documentary role produces a compilation error? 
It's quite annoying to have Lombok annotations that don't actually do anything when you'd think they would.

**Comment by rzwitserloot** [comment]
Hmm. Lombok _potentially_ does things with a `@NN` annotation in the following places:

* If it is on a field, then the field is considered 'required' for the purposes of `@RequiredArgsConstructor`, and any generated constructors will null-check. Of course, if there isn't a `@RequiredArgsConstructor`/`@AllArgsConstructor` (or a virtual one via `@Data` or `@Value` or even `@Builder`), and also no setter (which also does that nullcheck) then effectively the annotation really _does not do anything_.
* If it is on a parameter, lombok generates a nullcheck. Unless, of course, it can't; for example, if it is on a parameter of a non-defaulted interface method, where you obviously can't have any code.

In all other places, such as on a method (or ambiguously, its return type, either way), it does nothing other than serve a documentation purpose.

So, my problem with this proposal, @Yith1, is that the edge cases are clear enough:

* If it is clear the annotation does nothing and couldn't possibly do anything ever (such as in `public @NonNull String foo()`), then if you ask lombok to warn about pointless NN annos, then clearly, warn.
* If it is clear the annotation does something specific, such as `@Value public class Foo {@NonNull String name;}`, then clearly do _not_ warn.

Which leaves:

* What if the annotation does not _actually_ do anything _right now_, but even fairly slight and mostly unrelated code changes make it do something later? For example: `public class Foo {@NonNull @Setter String name; public void setName(String n) { ... }}`. Here NonNull seems to do something (namely, add a null check to the generated setter) except it doesn't actually because the setter annotation doesn't do anything (which does get you a warning here). It would actually be very very difficult (as in, a complete redesign of how a lot of this stuff works) to tell you that therefore the `@NonNull` now _also_ doesn't actually do anything.

We have two options here:

* That last thing isn't the right choice - any place where `@NonNull` is used where it _could_ mean something even if it currently actually doesn't, we allow it. We'll need to do work on cornercases - is annotating a field with `@NonNull` when no other lombok annos exist _at all_ in that file 'definitely useless' or merely 'potentially useless'? - therein lies the rub: We have to make up definitions and these won't necessarily be clear to users. Will users intuit the same rules? If they turn on 'warn me about pointless `@NonNull` will they understand the difference between 'definitely useless here' and 'possibly does stuff but not right now'? I doubt it.
* That last thing IS the right choice. We don't want to implement wrong choices out of convenience, but making lombok warn that some `@NonNull` anno is not _actually_ having any effect just doesn't fit the modular nature of how lombok is designed right now so this is a huge (like, a month, something like that) task which I rather doubt crosses the work v. effort bar.

Hence why I'm hesitant.

One easy way out is to offer specifically a config key that says 'warn if methods/non-param types are annotated with it'. i.e:

```
private @NonNull List<@NonNull String> x;
```

Here we don't warn about the field even if there are no other lombok annos, but we DO warn about the second `@NonNull` because that doesn't do anything and (unless we add new lombok features) never will.

This would be easy to implement and not particularly confusing. However, what should the name of the config key be? I'd be nice if it conveys the idea without being a key that's 160 characters long. I can't think of a good one and without a good name this isn't a good idea.

**Comment by Yith1** [comment]
@rzwitserloot thanks for your analysis. I can see that this is a much more complex issue that I originally thought.

It's really the following case that I was thinking of mainly.
```
public @NonNull String foo())
```
i.e. Only really the case that this specific issue is about. The case where ideally we'd have been able to say that the annotation could not be applied at all.

As for the name, then that's an interesting problem. We could just deal with this one case perhaps?
Something like:
```
lombok.warnOnMethodReturnNonNullAnnotation=true
```

You could go more generic and then explain what exactly is triggered in the documentation. 
```
lombok.warnOnUselessNonNullAnnotation=true
```

**Comment by rzwitserloot** [comment]
@Yith1 wrote:

> It's really the following case that I was thinking of mainly

Understood. Unfortunately we don't have that luxury :(

> `lombok.warnOnMethodReturnNonNullAnnotation=true`

I'm pretty sure if we're gonna do this, it needs to cover type use as well (the `@NonNull` in `private List<@NonNull String> field;`)

`lombok.nonNull.warnIfDocumentary = true` is a possible option, with docs that explain that any usage on return types / type-use is considered 'documentary'.
