### ISSUE TITLE
[FEATURE] Builder/SuperBuilder `setterPrefix` configurable from lombok.config

### ISSUE THREAD

**Issue by mickroll** [projectlombok/lombok#3159]
As there is the `@Builder(setterPrefix = "...")` option, it would make sense to have the ability of setting it once across the project at the `lombok.config`.
An example would be using `lombok.builder.setterPrefix = set` to have a project-wide prefix `set` for bean-like builder access.
For consistency, the config value should be used as default value by `@SuperBuilder` as well, just like `lombok.builder.className` is used by `@SuperBuilder` already.

Justification:
- Improved signal-to-noise ratio
- Better readability (arguably)
- Helps keeping project convention consistent

BTW this feature request somewhat follows #2849, to have a project wide consistent config for (very) often used lombok features.

**Comment by rzwitserloot** [comment]
We won't do this. The reason we offered it in the first place is if you're making a builder that needs to fit specific needs, e.g. because it has to implement an interface or you're using it with some backwards library that expects silly defaults.

Specifically, `with` (the common prefix) is, in our opinion, highly misleading. There's no point in having a lombok.config setting other than 'I want to apply it everywhere regardless of circumstance' and we're not (currently) seeing the point of that. Builder is in its infancy, relatively speaking. 'there are many ways to do it' engenders pointless style quibbles and needlessly increases learning curves.

We like the java community and wouldn't want to make it worse by introducing pointless customization options like that.

**Comment by topr** [comment]
@rzwitserloot this would be very helpful though. The overarching idea behind Lombok is to reduce boilerplate and noise in code, isn't it?

So now needing to add a specific param by in each every `@Builder` is counter-effective to achieving that goal and also makes it much tougher to keep a codebase consistent.

I appreciate your great input into java community but your position in which you think you know better what application, code style, or any other issue anyone may face or need is not very considerate, is it?

Here's an use case in which Lombok's default builder name convention doesn't work very well.

Prod code in Java
```java
@Builder
record Something(@NonNull String foo, @NonNull Integer bar) {}
```

Test fixture DSL in Groovy
```groovy
class SomethingDsl {
    @Delegate
    private final SomethingBuilder builder = Something.builder()
            .foo('foo-1')
            .bar(1)

    static anySomething(@DelegatesTo(SomethingDsl) Closure definition) {
        new SomethingDsl().tap(definition).build()
    }

    // some convenience setters delegating to builder for improved SNR on the test use side
}
```

Test code in Spock
```groovy
given:
def foo = "any-foo"

when:
def something = anySomething { // statically imported from SomethingDsl
    foo foo // here is the problem where the name of local variable clashes with the default setter name so this doesn't work
}

then:
// whatever the assertion
```

If the DSL's underlying builder had any setter prefix, the clash wouldn't happen, i.e.  `setFoo foo` or `withFoo foo`.

I've been now going through multiple in our organization (some quite large) for a couple of years to ensure that explicit `setterPrefix` is on each and every `@Builder` so that it matches project/organization convention, and also chasing other devs about it. But it's tedious and like whack-em-all 😔 

A global configuration option would really save a lot of otherwise unnecessarily wasted time, effort and noise in code 🙏
