### ISSUE TITLE
[FEATURE] provide getters in generated builders

### ISSUE THREAD

**Issue by mickroll** [projectlombok/lombok#3160]
Lombok generated builders are super-useful. In our current project we pass them around, partially fill them using mapstruct or custom code and finally call `.build()` to get the target object.
Sometimes code that modifies a partially filled builder relies on data that was already set into the builder previously. But this is not accessible, as the builder offers no getters. So we pass that data around alongside the partially filled builders. This duplication of course leads to inconsistencies, bugs, ....

It would be neat to be able to access the builders data (set or still unset) without constructing the target object. The latter may not be feasible if `@NonNull` fields are still unfilled.

Proposal:
- generate a getter for each property in a builder, just like `@Getter` would do on a pojo: `public [type] get[PropertyName]() { return [propertyName]; }`
- if needed (for backwards compatibility or the likes), enable this generation with a switch in `@Builder(getter = true)`/ `@SuperBuilder(getter = true)` and `lombok.config`: `lombok.builder.getter = [true/false]`

**Comment by rzwitserloot** [comment]
We're not doing this. For two specific reasons:

* That's not what builders are for. They aren't proxy mutable variants of the underlying concept. If builders have getters, well, what about 'calculated' getters? Say the normal object has both a `.getSocialSecurityNumber()` method (which is 'just' a getter) and also has a `.isSocialSecurityNumberValid()` method, which isn't a usual getter (there is no boolean field named `socialSecurityNumberValid` - instead, it checks if the field `socialSecurityNumber` is non-0/non-null and the number there passes the 11-test or whatever checksum mechanism is present. It would make complete sense that you'd want that to just exist in the builder as well, but, how? You could make an argument that - no - the builder is _not_ an ersatz mutable variant, it merely represents the concept of building the thing you're building, but that concept could report on what it would use for the `socialSecurity` value if you would `build()` it. But, to me it is rather obvious that this important yet esoteric distinction will be lost, and we'll get 1000 issues adamantly requesting all sorts of things because of their flawed view that builders are ersatz mutable variants. Whatever makes you think you needed it - it means lombok's builder support isn't what you're looking for. It's no longer boilerplate.
* Not everything is a simple property. Specifically, `@Singular` makes a complete hash out of this - take, for example, hashmap construction via singular. __We do not even have a map__ during construction - we have 2 lists. This lets us give you an efficient map that doesn't eat up needlessly large memory. Introduce the notion that you can actually `get` from the builder and it now gets really nasty. Do we:

* Perform the task of building up the map every time you call the getter (or possibly - we cache it, but once you add more items, we discard the cache)? That means `.getMap()` would have quite significant overhead. I __strongly dislike__ libraries that have surprisingly nasty performance characteristics in places where it really isn't at all obvious, hence this is an easy veto.
* Just don't have them for `@Singular` stuff. But that's weird. Why do builders have getters for everything _except_ the `@Singular`s?
* Error out if you attempt to make getters for a builder that has 1 or more singulars in it. But that's kinda weird too. It certainly is a surprising limitation.
* Rewrite the Singular impl to act completely differently if a getter is needed - and just build up the map as normal and either accept that the end result will not be properly packed in, or repack it on build, or transform it on build - if there was a way to do it exactly equally as efficient as our current 'make 2 lists then pack them into a map upon building' approach we'd just do that: There isn't, so now you get this weird 'how it works under the hood is completely different, due to a seemingly utterly unrelated thing, namely: Whether you want a getter or not'. It also massively complicates our tests and code, as the codegen now goes through a choose-your-own-adventure style book. Easy veto.

I don't see a way forward on this,hence, closed.

**Comment by mickroll** [comment]
Thanks for taking your time for a detailed explanation!

> this important yet esoteric distinction will be lost, and we'll get 1000 issues adamantly requesting all sorts of things because of their flawed view that builders are ersatz mutable variants

I see, getters on builders would open up a whole new field for feature requests what builders should be able to do additionally.

> Not everything is a simple property. Specifically, `@Singular` makes a complete hash out of this - take, for example, hashmap construction via singular. We do not even have a map during construction - we have 2 lists.

One could rewite `@Singular` to use a custom `Map` implementation, that internally uses a simple `List<Entry<?, ?>>`.... but i get the point. This would be a large rewrite.
