### ISSUE TITLE
[BUG] Lombok installer crashing on Adoptium JDK 17

### ISSUE THREAD

**Issue by MansenC** [projectlombok/lombok#3171]
**Description**
This bug crashes the lombok installer UI completely after a few seconds due to a stack overflow. The attached file describes the bug with lombok 1.18.20 but the exact same thing happens on 1.18.22, too.

**To reproduce**
I am having the Adoptium JDK 17 in x86 installed on this machine. I simply downloaded the latest lombok version, executed the jar file, after a few seconds it crashed. This happens in the eclipse directory aswell and the application can be instantly crashed by clicking the "Specify location" button. Here is the attached error pid:
[hs_err_pid14528.log](https://github.com/projectlombok/lombok/files/8463665/hs_err_pid14528.log)

**Expected behavior**
I'm pretty sure that the application should keep running

**Version info**
- Lombok Version 1.18.20 and up are at least affected
- OS is Windows 11 64 Bit
- Java Version is Adoptium JDK 17.0.2 x86

**Additional context**
It seems like the crash happens natively inside AWT so I am not sure if this is a lombok related or JDK related issue, nevertheless eclipse is running just fine, that's why I am reporting it here first. As expected with an AWT related issue, thos only applies to the lombok installer UI, the command line API works without issues. I tried searching for a way to force the lombok UI to print debug information to the console but I didn't find any way, neither by google nor by source code. So if there is any I can provide the output. Overall this seems like a very specific issue given my oddly specific circumstances of requiring an x86 version of Java on a 64 bit machine.

**Comment by rzwitserloot** [comment]
It's a java AWT bug evidently. I can't reproduce it, nor can I fix it. There's a small chance 3 manmonths of exquisite work to try to work around whatever this is, and which will be effectively untestable without another 3 manmonths to set up the exact environment, bugs and all - will do it. We're not interested in trying to write or maintain such a beast.

There's always `java -jar lombok.jar install /location/to/your/IDE` which is the all-command line take on the ordeal.

If there was an easy way to tell the user to do this, I'm game, but I assume most ways of running the jar in GUI mode mean there is no console we can send anything to, and given that the UI is crashing, we're stuck there too. We can't catch an exception because, well, hs_err_pid file. That by itself kinda gives the game away: If simple java code could reliably hard-crash the VM like that, then that'd be _wild_. Makes it a slam dunk case this isn't lombok's fault, adoptium17 on your platform is broken.
