### ISSUE TITLE
Undocumented (or confusing) behaviour of  Lombok generator with org.jetbrains.annotations.NotNull

### ISSUE THREAD

**Issue by trokhinas** [projectlombok/lombok#3305]
I tried to use `org.jetbrains.annotations.NotNull` for static code analyse by IDEA like this:
```
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

@Data
@NoArgsConstructor
public class LombokTest {
    @NotNull
    private String field1;

    @Nullable
    private String field2;

    public static void main(String[] args) {
        final LombokTest test = new LombokTest();
        test.setField1(null); // <-- here throws an exception
    }
}
```

But when i tries to call `test.setField1(null)` i got an exception:
```
Exception in thread "main" java.lang.NullPointerException: field1 is marked non-null but is null
```
It seems like Lombok intepret any NotNull annotation for generating null checks or it is a bug? If i would want to add null checks i would use `lombok.NonNull` that was designed specifically to GENERATE checks in source code. But i just want to use advantages of static analyse by IDEA and do not want any real null checks.

**Comment by trokhinas** [comment]
I am using Lombok 1.18.22 and Lombok 1.18.12.

**Comment by marc-guenther** [comment]
Different people like different behaviour. See #3294 for comparison. ;)

Also I'm confused now. Apparently `org.jetbrains.annotations.NotNull` and `javax.validation.constraints.NotNull` are treated differently by Lombok?

**Comment by trokhinas** [comment]
@marc-guenther, integration with other libraries and frameworks is always cool. But as I said, if I want to force null checks on my objects, I would rather use `lombok.NonNull` as it was designed for that. First I want to find out if there is any documentation for this function or if it is an unexpected lombok generator behavior and a bug.

The only solution I've found so far is to "de-lombok" this code with IDEA.

**Comment by trokhinas** [comment]
In the lombok changelog, the latest entry states that 'BUGFIX: Turns out treating @NotNull as an annotation that indicates lombok should generate nullcheck guards causes all sorts of problems.' in [v0.10.2 (November 1st, 2011)](https://projectlombok.org/changelog#:~:text=v0.10.2%20(November%201st%2C%202011)). But nothing about `org.jetbrains.annotations.NotNull`. Is there a chance that the problem is related to the same name for the annotations?

**Comment by prdoyle** [comment]
It is documented [here](https://projectlombok.org/features/NonNull):

> Lombok has always treated various annotations generally named @NonNull on a field as a signal to generate a null-check if lombok generates an entire method or constructor for you, via for example @Data.

Question: why would you want to allow `setField1(null)` if `field1` is marked `NotNull`?

**Comment by prdoyle** [comment]
I think I answered my own question from [this change](https://github.com/projectlombok/lombok/commit/782daa49979c35cd93139b3cfbc98eafe346f790#diff-b633c3c8f5531eadfb5060e8987428890f7747b85a0acdd20d3eda28284748e6R75):

> NB: 'notnull' is not part of the pattern because there are lots of `@NotNull` annotations out there that are crappily named and actually mean something else, such as 'this field must not be null _when saved to the db_ but its perfectly okay to start out as such, and a no-args constructor and the implied starts-out-as-null state that goes with it is in fact mandatory' which happens with `javax.validation.constraints.NotNull`.

**Comment by trokhinas** [comment]
> It is documented [here](https://projectlombok.org/features/NonNull):
> 
> > Lombok has always treated various annotations generally named `@NonNull` on a field as a signal to generate a null-check if lombok generates an entire method or constructor for you, via for example `@Data`.
> 
> Question: why would you want to allow `setField1(null)` if `field1` is marked `NotNull`?

Test purposes

**Comment by trokhinas** [comment]
> It is documented [here](https://projectlombok.org/features/NonNull):
> 
> > Lombok has always treated various annotations generally named `@NonNull` on a field as a signal to generate a null-check if lombok generates an entire method or constructor for you, via for example `@Data`.
> 
> Question: why would you want to allow `setField1(null)` if `field1` is marked `NotNull`?

There is key difference! Documentaion says about NonNull annotation designed specifially for lombok purposes, but i don't use it! Why lombok NonNull is ever exists if lombok generate cheks for every pattern matching annotaion? Thats kinda strange..

**Comment by prdoyle** [comment]
I'm not sure; presumably because not everyone wants to ship with a runtime dependency on Lombok-specific annotations?

**Comment by rPraml** [comment]
The behaviour is also a bit inconsistent regarding on method annotations.
```java
public class TestAnnotation {
	@Test
	void testJetbrains() {
		jetbrainsNotNull(null); // <- will not fail. I would expect that it will fail
	}

	@Test
	void testJetbrainsOnSetter() {
		final LombokTest test = new LombokTest();
		test.setField1(null); // <- will fail
	}

	@Test
	void testLombok() {
		lombokNotNull(null); // <-- will fail (works as designed)
	}

	void jetbrainsNotNull(@org.jetbrains.annotations.NotNull String jetbrains) {
		
	}

	void lombokNotNull(@lombok.NonNull String lombok) {
		
	}

	public class LombokTest {
		@Setter
		@org.jetbrains.annotations.NotNull
		private String field1;
	}
}
```

The problem in `void jetbrainsNotNull(@org.jetbrains.annotations.NotNull String jetbrains)` is, that [HandlerLibrary](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/javac/HandlerLibrary.java#L247) tries to call `resolver.typeRefToFullyQualifiedName(node, typeLibrary, rawType)` which returns null.

For me, I like that lombok checks also `@org.jetbrains.annotations.NotNull` but this should work consistent in all places.
I agree, that the behaviour maybe should be switchable

**Comment by rspilker** [comment]
@prdoyle Lombok should never be a runtime dependency

**Comment by rzwitserloot** [comment]
@trokhinas wrote:

> It seems like Lombok intepret any NotNull annotation for generating null checks or it is a bug?

Not 'any'. A certain well-known list of annotations that strongly imply a direct correlation between "the value is `null`" and "a bug has occurred; that should never happen; this state is nonsensical and semantically meaningless."

Specifically, for `@RequiredArgsConstructor` and lombok generating a 'setter' (a thing that takes in a param and assigns it to a field, so, setters, withers, and constructors), lombok works like that. We try to maintain this list and you can use `lombok.config` to modify it.

In contrast, if you want lombok to generate a nullcheck for a parameter in a method, specifically only `lombok.NonNull` will do.

This behaviour might be confusing but it is what it is. It has advantages. It's not simple to determine what behaviour would be best, which means the status quo wins, because the status quo gets 'does not break existing stuff' for free.

> In the lombok changelog, the latest entry states that 'BUGFIX: Turns out treating https://github.com/NotNull as an annotation that indicates lombok should generate nullcheck guards causes all sorts of problems.'

That's old news. The 'problems' that this entry refers to, is that not every annotation named `@NotNull` or `@NonNull` __actually__ implies what I wrote before (that if the field turns out to hold `null` at any point in time after construction has completed, that this implies "a bug has occurred; that should never happen; this state is nonsensical and semantically meaningless.").

A trivial example is JPA (hibernate)'s `@NotNull` annotation. That merely means: "When generating a `CREATE TABLE` SQL statement, include the proper SQL to add a NOT NULL constraint to the column representing this field". There __IS__ a semantically valid interpretation of an instance of that class holding a `null` value: This object is representing a row-to-be (it hasn't been `save()`d yet, and would fail if you try); it is not in an SQL-valid state yet but that's fine, as it's a tool to create a row, and the tool hasn't reached that phase yet. In other words, the lifecycle of this object can be in an invalid state, that its purpose. The semantic explanation is simply 'row not finished yet'.

Another example is validation frameworks - the semantic explanation for a `@some.validation.framework.NotNull` marked field being `null` is obvious: It represents input from an external system or from a user. Sure, that input isn't valid. But the semantic meaning is clear: Instances of this class represent what a user entered into a form. `null` means the user didn't pick a value for, say, an HTML `<select>`, or whatever. The semantic meaning is clear - and the validation framework will ensure that the business process being modelled will not advance beyond this phase.

This is in sharp contrast to e.g. intellij's `@NotNull` which has the aim of ensuring that the object is never `null` to begin with.

If this explanation is unclear, then that's a sad state of affairs but it is what it is, you will not convince us to move our opinion without being familiar with this nuance.

@marc-guenther wrote:

> Also I'm confused now. Apparently org.jetbrains.annotations.NotNull and javax.validation.constraints.NotNull are treated differently by Lombok?

See the above paragraph. Yes, they are treated differently. Yes, that is intentional. Yes, this behaviour is correct (as in, you want it to work this way. If you think it shouldn't, you either don't understand what validation frameworks do, or I don't).

@trokhinas wrote:

> test purposes

When you write `public void foo(String name) {}`, do you write a unit test to double check that if you pass an inputstream to the `foo` method that some failure occurs?

Of course you don't - you can't compile that. You trust the 'basis' - in this case, the combination of `javac` and the JVM class verifier ensuring that this contigency case __cannot__ occur.

Hence, 'test purposes' doesn't appear to make much sense here. It __cannot__ be `null` - unless you yourself write explicit code that sets it to `null`, e.g. with a direct field write (because lombok's generated constructors and setters won't let you do that).

You don't test for impossibilities. If you disagree with that sentiment and you feel that it is necessary, I don't really know what to tell you. Work on your imagination, perhaps? It is not possible to test for impossibilities; there are far too many (an infinite universe of them, in fact). Hence, if you think you are testing for everything including those, no, you aren't. That's not an ideal you should be chasing.

Lombok is opinionated in the sense that lombok aims to only include __boilerplate busting__ - a combination of something that comes up a lot + takes a lot of effort to write without lombok.

A crucial aspect of that is _comes up a lot_. It's hard to come up with a use case for this (and 'testing purposes', as outlined above, doesn't cut it). It doesn't matter that you cook up some exotic scenario where it's useful: We do not cater to exotic scenarios.

@trokhinas wrote:

> Why lombok NonNull is ever exists if lombok generate cheks for every pattern matching annotaion? Thats kinda strange..

For two reasons:

* `@lombok.NonNull` is the only annotation that will generate a null-check on arbitrary parameters. (in contrast to lombok-generated setters/withers/constructors, where any nullity annotation that strongly implies 'should not ever be null' does that).
* To avoid having to pull in another dependency. The JDK core libs don't have a nonnull annotation.

The title of this issue is 'undocumented'. It isn't.

**Comment by prdoyle** [comment]
@rzwitserloot - thank you for taking the time to write this comment. It is very clear.

The trump card here is this:

> you can use `lombok.config` to modify it.

So, when all is said and done, people can set the desired project-specific behaviour. I think that means we're really just arguing over documentation at this point. 😄

**Comment by rPraml** [comment]
@rzwitserloot in addittion to prdoyle's answer:

Would it make sense, if I update PR #3525, so that the users can opt-in with a config-key? 

I totally understand, that the PR is a bit dangerous, as it will really break things when other non-nulls were used in a "wrong" way (wrong = depends on the developer's perspective) 

Regardless if the PR will be merged or not, I would like that the documentation should be more clear in this point. For example:
----
Important: Various NonNull annotations on fields are recognized only by lombok generated code (setters and constructors.) 

Null checks in self written functions and constructors are only generated for lombok.NonNull annotations. This has historic reasons and will not be changed. (OR This can be changed with config key X....) 
----


Roland
