### ISSUE TITLE
[BUG] Incorrect test output for logger + records 

### ISSUE THREAD

**Issue by Rawi01** [projectlombok/lombok#3327]
**Describe the bug**
The first parameter of all tests with loggers on records is wrong.

This happens because lombok adds the generated logger field as first child but eclipse expects that the record components are the first fields. I don't think that this affects the actual compilation result. 

I also noticed that the output is different in recent eclipse versions, we may need to introduce a new directive to handle that.

**To Reproduce**
https://github.com/projectlombok/lombok/blob/c99e6bbeb513c51c68695dcc97fb683423205201/test/transform/resource/after-ecj/LoggerSlf4jOnRecord.java#L3

**Expected behavior**
The generated compact construct only contains the record components.

**Comment by rzwitserloot** [comment]
Yup, eclipse belatedly fixing their prettyprinter is rather annoying. An alternative solution is that we take the _current_ eclipse pretty printer which is pretty nice, and include it directly in the lombok test suite, so that we always use this (instead of 'whatever the prettyprinter is that ships with the ecj/eclipse version we are testing right now), and thus avoid having to add more directives.
