### ISSUE TITLE
[BUG] @ToString generates bad String if field marked as "@NonNull T @NonNull [] name"

### ISSUE THREAD

**Issue by kigo-qqw** [projectlombok/lombok#3416]
**Describe the bug**
`@ToString` annotation generates bad String 

code:
```java
@Value
class Foo {
    @NonNull String @NonNull [] strings;
}
log.debug("Foo : {}", new Foo(new String[]{"foo", "bar"}));
```

Output:
```
Foo : Foo(strings=[Ljava.lang.String;@293bc4da)
```

**Version info:**
 - Lombok 1.18.26
 - javac 20.0.1

**Comment by dstango** [comment]
Looks like the default output of toString() of an array and doesn't seem to be related to `@NonNull`.
I'd suggest to not use an array but e.g. a List that usually has a proper toString()-implementation.

Otherwise it would be a feature request to have a different output of arrays in the generated toString()-method, about which the Lombok developers would have to decide if that would be something to implement.

**Comment by Rawi01** [comment]
There already is some handling for arrays:
https://github.com/projectlombok/lombok/blob/250bc0660b09fbc8678309651a12bb0d93858340/src/core/lombok/javac/handlers/HandleToString.java#L214-L220
This is also mentioned on the feature page but it seems like the array detection is broken if there are type annotations.
