### ISSUE TITLE
[BUG] lombok 1.18.28 does not work with Eclipse 2023-06 (4.28.0)

### ISSUE THREAD

**Issue by tilothiele** [projectlombok/lombok#3451]
Eclispe doesnt find generated methods (builder(), getXXX()) provided by lombok.

I installed lombok 1.18.28 in eclipse 2023-06 via instaler -> added 

-javaagent:/......../jee-2023-06/eclipse/lombok.jar

to eclipse.ini. The getter an builder methods (provided by @Getter, @Setter, @Builder annotation) are not found by eclipse.
Also (afaik) the help about page should give a hint that lombok is installed. But nothing appears.

This issue has been described previously but is marked as resolved.
So, is this a new issue? 
Or did I miss a critical piece?

**Comment by dstango** [comment]
lookes like the ini path is wrong:
after installing via installer I get something like:
```
-javaagent:C:\Java\eclipse\plugins\org.projectlombok.agent_1.18.28/lombok.jar
```

When installing with the manual installer the path looks similar to what you wrote.

Maybe somewhere there's the trouble ...

**Comment by tilothiele** [comment]
> lookes like the ini path is wrong: after installing via installer I get something like:
> 
> ```
> -javaagent:C:\Java\eclipse\plugins\org.projectlombok.agent_1.18.28/lombok.jar
> ```
> 
> When installing with the manual installer the path looks similar to what you wrote.
> 
> Maybe somewhere there's the trouble ...

you are right. I didn't paste the complete path (intentionally). Here is the complete entry:

`-javaagent:/work/opt/eclipse/jee-2023-06/eclipse/lombok.jar`

**Comment by tilothiele** [comment]
Yes, that is exactly what I did:
* download/install a fresh and latest Eclipse.
* download and install the latest lombok

the line
`-javaagent:/work/opt/eclipse/jee-2023-06/eclipse/lombok.jar`

has been created by the lombok installer.

**Comment by tilothiele** [comment]
Hey!
I moved lombok.jar in the plugins subdir and changed the line accordingly to 

`-javaagent:/work/opt/eclipse/jee-2023-06/eclipse/plugins/lombok.jar`

It works now. :-)

**Comment by tilothiele** [comment]
Thaks a lot for your replies.

**Comment by tilothiele** [comment]
In the 'About Eclipse IDE' Panel now this appears (as I expecte):

Lombok v1.18.28 "Envious Ferret" is installed. https://projectlombok.org/

Does Eclipse refuses to load jars outside the plugins folder?

**Comment by dstango** [comment]
> Does Eclipse refuses to load jars outside the plugins folder?

no, I don't think so (unless there is an issue with access rights to the files). The parameter gets handed to the jvm, and treated accordingly.

Please re-read my previous message: I think it might rather be an issue of the eclipse launcher, that might *not* re-evaluate the ini file, when simply doing a restart from within eclipse. Probably because plugins usually don't install the way lombok does: lombok needs to hook in intimately with java to provide Eclipse with the features required in the IDE.

You might simply check if this is true (I'm just guessing): start Eclipse, remove the lombok-line temporarily from the ini file, click File -> Restart in Eclipse. If I'm right, lombok should still be shown in the about dialog, as the ini was not re-evaluated. As soon as you exit Eclipse and start if freshly, lombok should have disappeared from the about dialog....

**Comment by tilothiele** [comment]
Yes, I did restart eclipse several times. In both ways: File -> restart, and terminate/start manually.
