### ISSUE TITLE
[FEATURE] Named null setter / clear function

### ISSUE THREAD

**Issue by JordanGibson** [projectlombok/lombok#3472]
**Describe the feature**
This proposed feature is a flag which can be annotated on fields in a class which would generate a method for setting the field to null - this would probably either be as a flag in the existing `@Setter` annotation or a new annotation.

Current Lombok Code
```
class SomeContext {
    @Getter @Setter private Value someValue;
}

// clearing down someValue
someContext.setSomeValue(null);
```

Proposed Feature
```
class SomeContext {
    @Getter @Setter @Clearable private Value someValue;

    // or
 
    @Getter @Setter(nullSetterPrefix = "clear" or nullSetter = true) private Value someValue;
}

someContext.clearSomeValue();
```

**Describe the target audience**
This will be useful in scenarios involving Java classes containing fields that need to be set to null in a standardized way. By introducing the `@Clearable` annotation (or similar), the proposal aims to provide a more convenient method for setting fields to null. The feature can be especially valuable in scenarios where classes have multiple fields that require frequent nullification.

**Comment by Rawi01** [comment]
Have you thought about how it should handle collections? Simply applying `null` is easy but I would not expect that behaviour for a `List` or some third party collection library.

**Comment by JordanGibson** [comment]
> Have you thought about how it should handle collections? Simply applying `null` is easy but I would not expect that behaviour for a `List` or some third party collection library.

@Rawi01 not something I had considered, but I agree that the term clearing implies that a collection would be cleared down and i think that makes sense in that scenario. alternatively - there could be a configurable "clear" value specified in the annotation, that when an item is cleared down, it's value is assigned.

**Comment by rzwitserloot** [comment]
Unfortunately we have to deny this request.

The problem is a fundamental misunderstanding of what `null` is for. Or, rather, that the java community _itself_ is hopelessly confused about what `null` _actually_ means.

Going by the JLS and only by the JLS, `null`'s semantic meaning is:

* An uninitialized non-final field, or
* A 'slot' in a non-primitive array that hasn't been set yet.

You'll find no further philosophical waxing about what it is supposed to mean than that.

Contrast to SQL which is far more clear about it: `NULL` in SQLese means UNKNOWN, and therefore, it is entirely justified and logical that `NULL` in SQLese is infectuous. Even `x = TRUE` in SQL has 3 possible values (namely, `TRUE`, `FALSE`, and `NULL` - and even `NULL = NULL` doesn't evaluate to `TRUE` - it evaluates to `NULL`). This is sensible, eventhough this is the butt of many, many jokes about SQL, if you keep in mind what null actually means. if I ask you: I have the name of a person in my mind. I'm not going to tell you what it is and there is no other way for you to know what it is. Then someone asks you: Is Reinier thinking of "Jordan", you cant answer 'TRUE', and you can't answer 'FALSE'. you do not know. You can only answer "I don't know" - and `NULL` is the value in SQL-ese that conveys this.

If you apply the SQLese understanding of java, then you have a really, really big problem here: "Clear the value" __isn't necessarily the same semantic idea__ as 'unknown'. The JLS meaning of `null` is essentially useless ("the field is not set" is semantically meaningless; that is an implementation detail). The java community meaning of `null` is a total mess. If I search all github projects for `if (x == null || x.isEmpty())` I get half a billion results which is __utterly bizarre__ because that is hopelessly confused (i.e. really bad) code. If 'null' and 'empty' mean the same thing why is the state of this object in such a state? Why isn't x simply 'the empty string'? It can't be 'for performance reasons', because the JVM has an empty string ref floating around already.

To show you how much this semantic notion kills this idea, you tell me:

Given: `String name;` - if I ask "The name has been cleared - so, what is its value?" at a java conference or some such, I bet I get a nice even split: Half of the folks I ask will absolutely insist that must mean `name.equals("")`, and the other half will be thoroughly convinced that this must mean `name == null`.

So, we introduce a style war (should one call `.setName(null)` or `.clearName()`? It's bad to introduce 2 ways of doing things when they are pretty much equally easy to write and read and neither has a clear advantage or disadvantage), _and_ introduce loads of confusion. Whereas `.setName(null)` at least isn't confusing: If I ask that at a big conference, everybody will correctly surmise this code must mean `name == null` is true, and `name.equals("")` is false / throws.

Also, whilst the SQL 'null means unknown' is not particularly popular in java, it is "correct", in that the behaviour that nulls have fits that model best: If I ask a nullref a question (I call a method on it), an exception occurs. That's a totally sensible thing to do if the reference implies "I do not know what this value is". i.e. given `String x = null;`, the notion that `x.length()` should probably return `0` fits the mental model that `null` is semantically equivalent to the empty string. However, this model is broken, in that java itself doesn't work that way, as `x.length()` would throw an NPE. The mental model of 'null means: unknown' fits java's actual behaviour far better: Ask questions about the nature of the unknown value, and exceptions occur.

Hopefully that context fully covers why the answer is: No, and any PRs that add this feature will be closed without comment other than linking to this issue.
