### ISSUE TITLE
[FEATURE] @Builder add nullBehavior as a parameter

### ISSUE THREAD

**Issue by Aszolus** [projectlombok/lombok#3489]
This would allow the updating of an existing object using the toBuilder() method to determine what behavior should occur if a field is going to be set to null in the builder.  This would help reduce boilerplate for the merging of objects in cases where the updating object can have null values that should not replace existing values.

**Comment by janrieke** [comment]
While I understand your feature request technically, I don't get the use case behind it. If you don't want `null` values to be set, why don't you simply add a check before? Or is it a library you are using that's missing this feature?

I'm asking because I see a problem with your request: The notion of `null` differs between developers. It could be, for example, "unset", "not yet set", "invalid", just a reference value (that's how the JLS defines it) or something in between or a mixture. If lombok loads semantics on this value beyond what's obvious, that's a save way of lombok users producing bugs. Especially if you cannot tell at all that there is something special with the method at the call site.

**Comment by dstango** [comment]
Just guessing what the use case might be:

Consider a REST PATCH request: you'll might get a Json body with only some fields provided. The corresponding POJO might then contain only these provided fields filled with values, while the others are set to null. 
If you then get some object from your persistence store and want to change only the non-null tfields from the POJO, this might be the intended use case.

Anyhow: I'd rather say that sounds more like a mapping frameworks job than lombok's ... E.g. as elaborated here for model mapper: https://stackoverflow.com/q/49153100

**Comment by Aszolus** [comment]
This isn't solving some major issue or anything.  I noticed that with the @Singular annotation, you can do @Singular(nullBehavior = NullCollectionBehavior.IGNORE) which will prevent a Collection from being set to null in the builder and thought that it could be useful to have that as a settable default for all builder fields.  It could reduce a lot of boilerplate null checks.
