### ISSUE TITLE
[FEATURE] Getters and Setters for Embedded fields

### ISSUE THREAD

**Issue by GonzaloMartinezSa** [projectlombok/lombok#3508]
Hi, I'm new to this, but I recently started working with Java and Spring Boot, using lombok's annotations, and I think there's something that should be added.

The simple description is this: I want to be able to create `@Getter` and `@Setter` for embedded fields just as easily as it is to create them for fields in your base class. This is related to `@Embedded` classes when connecting to databases, as you may change the model a bit taking into consideration the tables.

So for example, let's say that I have a class Person, that has multiple fields. Well, let's now say that one of the fields is of type Location. A class Location has a country, a street and other things. What can I do with lombok's `@Getter` and `@Setter` right now? Well, I can annotate everything with `@Getter` and `@Setter`, and call it a day. However, think of how I would access a person's country:
```java
person.getLocation().getCountry();
```

And this is worse if there is more than one thing embedded, so to speak. I don't know about you, but from all I learned over the years, this seems terrible. I don't care, when managing a person, if it has a Location inside, or anything for that matter, if I'm planning to ask a person the country in which they live, it should just be like this:
```java
person.getCountry();
```

In my case, it was particularly noticeable because I had an `@Entity` class with an `@EmbeddedId`, meaning the table's primary key was 'composite' (formed by 2 or more columns in the database). Here, I had to make a class to be used as an `@EmbeddedId`. I also didn't want to use this class as it is to make responses for clients, so for the sake of that I created a `PersonDB` and a `PersonModel`, the latter being the model that clients receive in responses.

The problem that I mentioned before appeared clearly here, when trying to construct a `PersonModel` from a `PersonDB` (following this example):
```java
public PersonModel(PersonDB personDb) {
  this.name = personDb.getPersonId().getName();
  this.email = personDb.getPersonId().getEmail();
  //...
}
```

So I quickly went and I changed the `PersonDB` code like this:
```java
@Getter
@Entity
public class PersonDB {
  @EmbeddedId
  PersonId personId;
  //...
  
  public String getName() {
    return this.personId.getName();
  }

  public String getEmail() {
    return this.personId.getEmail();
  }
  //...
}
```
So that now I can do this:
```java
public PersonModel(PersonDB personDb) {
  this.name = personDb.getName();
  this.email = personDb.getEmail();
  //...
}
```
And, in the end, I ended up creating boilerplate code, and for getters of all things! You can see why I post this here. I think that it alligns well with what lombok's `@Getter` annotation tries to do, and I also think this scenario isn't too uncommon, specially when dealing with databases. 

Maybe there's something already that solves this, but I don't know about it (if there is, just tell me). If there isn't, I ask for what you think about it and what about making a solution. Maybe something like `@Getter(embedded=true)`, or maybe another annotation?

Thanks

**Comment by rzwitserloot** [comment]
The problem is [resolution](https://github.com/projectlombok/lombok/wiki/LOMBOK-CONCEPT:-Resolution): We know that your `personId` field is of type `com.foo.PersonId`.

__But we do not know anything about _that_ type__. We don't _know_ it has a `getName()` method. To know that, the AST first needs to be resolved: The JVM isn't like C - you don't have to order your compilation process and work with header files. (C compilers are 1- o 2-pass: If some code calls `String.toLowerCase()` before the compiler has processed the `String.java` file the compiler bombs then and there stating that doesn't exist). Java instead works in rounds: First it parses __everything__, then builds up a simplified list of what everything has __totally ignoring actual source code__, and only then does it parse statements and the like. To avoid the C issue of needing to manage your passes.

But that puts lombok in a bind: If we wait until everything is resolved, well, then we're too late - we can't then add a method - the compiler has probably already errored out on someone calling a getter that we haven't made yet. If we add the relevant methods before then, we're on time, but then we don't _know_ what `PersonId` has so we can't implement this feature.

One easy solution is rounds - the ability to tell the compiler to start the whole process anew. This is harder than it looks, and is a severe time penalty (that makes compiling take a lot longer). We do it for a select few lombok features, but it's a high maintenance burden and a high performance cost.

Request, unfortunately, vetoed. We simply do not know how to deliver it in a way that the cost (in terms of maintenance burden, stability, and compile time it'll take) is worth the gain. Once we do, this and quite a few other common requests are top of the list.
