### ISSUE TITLE
[FEATURE] @Immutable for fields

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [projectlombok/lombok#3577]
It would be nice to have an extension that makes fields immutable. Basically generating a setter-method for a private field that contains the code to only set the field once. 

Why am I thinking about it?
In many cases I am not using `static final` fields because I want to write unit-tests that surround these fields with Mockito.spies to write assertions that the objects are called at the right moments with the correct params. For this reason I am normally making these fields immutable instead of static final.

**Comment by Rawi01** [comment]
Can you add some more details why you need this and a normal constructor is not sufficient? I also don't get why you mentioned `static final` fields (constants).

**Comment by rzwitserloot** [comment]
Use case denied. This isn't common enough.

If you want to change our minds, a few notes:

* Internet 'polls' are irrelevant. It doesn't matter if you find 500 people to chime in that they'd love this feature. It's a biased sample, and we do not submit to that kind of peer pressure. If it seems like you're starting a bit of a brigade, we'll double down on vetoing it just to make doubly sure bad behaviour isn't rewarded.
* We need clear use cases that indicate our opinion that this isn't common enough, is misguided. Which is _not_ a matter of 'well, I found 500 people with bizarre setups where this might be useful'. It needs to be something one might write into a 'book of patterns', or something listed directly in the main tutorial of some very commonly used library, for example.
* We don't like mockito much; usually good code design obviates the need for it. Lombok has a rule that features that have no obvious use other than something that is usually bad code style - are vetoed. Because that feature's existence is tacit approval for the bad code style (given that there's no other obvious use for the feature), and we don't wanna do that. I point this out simply to save you time: I doubt examples of how this mockito-based use case is common, will make us reconsider.
