### ISSUE TITLE
[FEATURE] new parameter for Setter to return old value.

### ISSUE THREAD

**Issue by jan-pesta** [projectlombok/lombok#3588]
**Describe the feature**
Please add parameter for generating setters to have a way to return previous value like follow:
```
public T setValue(T value) {
    T old = this.value;
    this.value = value;
    return old;
}
```

**Describe the target audience**
This is one of commons code I have seen in many projects where notification about value change are needed.

**Comment by rzwitserloot** [comment]
> This is one of commons code I have seen in many projects

I have never seen this.

> Please add parameter for generating setters to have a way to return previous value

No. Not boilerplate, and would be wildly confusing as the signature does not indicate what's happening; if a `setX` method returns anything but `void`, the go-to answer generally is that it `return this;` at the end, for chaining purposes, which lombok already supports. The feature would be confusing. "Is confusing!" is not a death warrant for a feature request, but it significantly elevates the bar that has to be crossed; it has to add a ton of value.

This doesn't. Not even close. PRs would be denied, and I doubt there'd be a point to convincing us otherwise. Note that popularity contests do not work (there is no point finding 100 people to chime in here. That's not a statistically relevant amount of java coders, that's not how we determine such things). Find objective, falsifiable cases. Such as popular (as per objective measures such as how often it shows up in other deps, web search results, github stars and the like) libraries that strongly lean towards _you_ writing setters this way, or major tutorials/books that espouse this kind of thing. I doubt they exist.

**Comment by jan-pesta** [comment]
Hi,
Same feature is used on Atomic Object with getAndSet method. I do not say it has to be setter, it could be getAndSet. 
I came with this feature request as there is no easy way to create own custom annotations, where I would be fine with it.

**Comment by rzwitserloot** [comment]
@jan-pesta the method is _literally_ called `getAndSet` to avoid all doubt. You could write a feature request for `@GetAndSetter`, which would produce for a field `String foo;` a method:

```
public String getAndSetFoo(String newVal) { String oldVal = this.foo; this.foo = newVal; return oldVal; }
```

Except:

1. This is not an acceptable name. `@GetterAndSetter` is _extremely_ confusing as I bet most people would incorrectly assume that means: Generate both a getter and a setter. Not "Generate a single method - a getAndSetter, which is neither a getter nor a setter but a weird amalgamation of it".
2. Not boilerplate.

We'd love for lombok to gain some features to make it relatively easy to add stuff to it on a plugin basis, but the effort required to get lombok there is epic. (years of work, I think). We don't have the resources to go quite that far I'm afraid :(
