### ISSUE TITLE
[FEATURE] Add new annotations for converting Java objects. For example: @ConvertTo({FooA.class, FooB.class})

### ISSUE THREAD

**Issue by fenghuanfun** [projectlombok/lombok#3617]
**Before submitting**
done

**Describe the feature**

Add new annotations for converting Java objects. For example: @ConvertTo({FooA.class, FooB.class}).

Currently developers usually use Mapstruct, BeanUtils or handwriting when converting objects. However, 

- BeanUtils has performance losses

- MapStruct is difficult to use，adds extra coding work

- handwriting can be very annoying

If lombok add this annotation to lombok, it will greatly improve the development efficiency of application developers, improve application performance, and avoid annoying handwritten getters and setters.

***Before***
```java
@ConvertTo({FooA.class, FooB.class})
@Data
public class Foo {
    private String name;
}
```
***After***
```java
public class Foo {
    private String name;
    // ... ignore getter and setter

    public FooA converToFooA() {
        FooA fooA = new FooA();
        fooA.setName(this.getName());
        return fooA;
    }

    public FooB converToFooB() {
        FooB fooB = new FooB();
        fooB.setName(this.getName());
        return fooB;
    }
}
```

**Describe the target audience**
Huge number of developers

**Additional context**
Is it possible to accept a pull request for this feature?

**Comment by Dinozavvvr** [comment]
I think you should better use mapstruct or model mapper instead

**Comment by rspilker** [comment]
This is hard to implement since it would require resolution: the types `FooA` and `FooB` would need to be resolved and inspected for their contents, and this has been problematic in the past.

Describing the target audience as "Huge number of developers" isn't helpful. I've personally never encountered the need for this. In what scenario would transferring all the data to a different type with the same data occur? I suspect when that's typically in the realm of Data Transfer Objects, where Mapstruct or similar tools should shine.
