### ISSUE TITLE
@Slf4j fails with static initializer

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#368]
_Migrated from Google Code (issue 295)_

**Comment by muued** [comment]
Today I tried to log something in an enum constructor which lead to a NullPointerException, because the log field was not yet initialized.
After reading this thread, it seems like trying to initialize the log field before the enum constants to be able to use it in their initialization process is not viable either.
If this is correct, it may be helpful to mention this circumstance on the feature page of the log annotation!

**Comment by tafit3** [comment]
Static field initializers in enums execute after the initializers of enum constants. This is a java language feature, so the hint on the feature page may be useful, but your problem is out of scope of lombok.

"It is a compile-time error to reference a static field of an enum type from constructors, instance initializers, or instance variable initializer expressions of the enum type, unless the field is a constant variable (§4.12.4)."
https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.9.3

However, if there is a static nested class, it will be initialized before the enum constants, so the following would work:
```java
enum Example {
    A, B;

    private static class $LogContainer {
        static Logger log = Logger.getLogger(Example.class.getCanonicalName());
    }

    Example() {
        $LogContainer.log.info("Initializing: " + name());
    }
}
```

Could lombok somehow replace the "log" with "$LogContainer.log"? Another (pretty ugly) solution is to name the nested class "log" and delegate all the calls:

```java
enum Example {
    A, B;

    private static class log {
        static Logger log = Logger.getLogger(Example.class.getCanonicalName());

        static void info(String message) {
            log.info(message);
        }
    }

    Example() {
        log.info("Initializing: " + name());
    }
}
```
