### ISSUE TITLE
[FEATURE] Generate composite records

### ISSUE THREAD

**Issue by depsypher** [projectlombok/lombok#3718]
It would be cool if Lombok could make up for the inability to extend records in Java by generating a composite record from another record you specify.

Plain Java:

    record Vehicle(int topSpeed, int passengers) {
    }
    
    record Bike(int topSpeed, int passengers, int wheels) {
        public Bike(Vehicle vehicle, int wheels) {
            this(vehicle.topSpeed(), vehicle.passengers(), wheels);
        }
    }

Lombok:

    @ExtendsRecord(Vehicle.class)	// generates the Bike record above
    record Bike(int wheels) {
    }
    
    // can create specifying all fields
    Bike bike = new Bike(50, 1, 2);
    
    // or by passing in a "base" record along with the extra parameters
    Vehicle twoSeater = new Vehicle(50, 2);
    Bike tandem = new Bike(twoSeater, 2);

**Comment by abdelhak-zaaim** [comment]
its looks a great idea,

**Comment by siemieniuk** [comment]
I think this is a very interesting feature which could be implemented.

This could make Java closer to C#'s record inheritance feature. The only thing which is not possible to implement is an abstraction layer, such like:
```
Vehicle bike = new Bike(50, 1, 2); // Impossible in Java, unless using classes
```

We should also remember that this syntax should definitely be allowed:
```
@ExtendsRecord(Vehicle.class)
record Bike(int wheels) {
    @Override
    public String toString() {
        return "Bike{"
            + "topSpeed" + topspeed
            + "passengers" + passengers
            + "wheels" + wheels
            + "}";
    }
}
```

…and also this one:
```
@ExtendsRecord(Vehicle.class)
record Bike(int wheels) {
    @Override
    public String toString() {
        return "Bike{"
            + "topSpeed" + topspeed()        // notice a difference with parentheses after a property
            + "passengers" + passengers()
            + "wheels" + wheels()
            + "}";
    }
}
```

Another thing to consider is allowing to write our custom method when the parent record has it already implemented (some kind of polymorphism), like in this snippet:
```
record Vehicle(int topSpeed, int passengers) {
    void greet() {
        System.out.println("Beep, beep!");
    }
}

@ExtendsRecord(Vehicle.class)
record Bike(int wheels) {
    void greet() {
        System.out.println("Ding, ding!");
   }
}
```

Last, but not least: access modifiers. Since some methods could depend on "parent" record, all private methods from parent class should also be generated in extended record. How should we deal with a case like parent - private, child - public? Should writing such a method be allowed with changing a modifier?

**Comment by rzwitserloot** [comment]
Records don't support this. Period. This is, at best, a hack, and one that has a ton of problems. Purely on the lombok side, we need [resolution](https://github.com/projectlombok/lombok/wiki/LOMBOK-CONCEPT:-Resolution) to implement the idea (how do you know that the constructor `Bike` with params `topSpeed` and `passengers` needs to be created so you can invoke the constructor of `Vehicle`? You don't; not without looking at Vehicle, which you can't, not without resolution.

Java-wise this is also a really bad idea. You __appear__ to have a hierarchy of types but you don't actually have them. Because `new Bike(1,2,3) instanceof Vehicle` would resolve to `false` which is wrong.

Idea vetoed.

**Comment by rzwitserloot** [comment]
If the fundamental issues _on the java / API design side_ can be solved, it's at least possible we'd in theory accept this feature (though, as long as resolution is required, the balance between maintenance burden and value is unlikely to mean we'd allow it anytime soon). However, given how records work, I don't think the API design issues here can be solved.

More to the point perhaps, lombok __already solves this__. records aren't classes. They have a very specific purpose, and "Oh, I know, I want to have a hierarchy of records!" __is not it__. But... _classes_ __are it__ and can be used to model this stuff just fine.

Everything that records give you ,and I mean __everything__, can be had with lombok. Hence, there is no point to any of this. Just make this:

```java
@Value @NonFinal class Vehicle {
  int topSpeed;
  int passengers;
}

@Value class Bike extends Vehicle {
  int wheels;
}
```

Now, that wouldn't _actually_ do what you want, __yet__, because lombok doesn't do that. But the only reason lombok cannot make that sing the way one would want, is because the chicken-and-egg issue of resolution makes it really hard to deliver. But the fix for that is to fix the resolution problem (which is fixable, just.. very hard to do so).

As they say, if you find yourself in a hole... stop digging. This'd be digging even deeper. Hence, I _really really_ doubt anything would convince us that this is a good idea.
