### ISSUE TITLE
[BUG] @Nullable not copied to @Builder setters

### ISSUE THREAD

**Issue by internetstaff** [projectlombok/lombok#3755]
Reference: https://github.com/projectlombok/lombok/issues/1570

This was fixed for most cases, but as noted in the comments, @Nullable is not copied to the Builder's setters, thus IDEs warn of assigning nulls to non-null fields.

This is still a problem in 1.18.34.

**Comment by mihalyr** [comment]
I have the same IDE (IntelliJ) warning when I use the builder:

![image](https://github.com/user-attachments/assets/73971ad0-1114-4324-ae07-7008037637c8)


But noticed that NullAway does not complain and builds the code fine. I am using the freefair lombok gradle plugin in my project. I checked the generated classes and I see the annotation in the decompiled code:

```java
    @Nonnull
    @Generated
    public LombokNullableBuilder value(@Nullable final String value) {
      this.value = value;
      return this;
    }
```

My suspicion is that this is in IntelliJ IDEA bug in the Lombok plugin. Because if I run the "Delombok" action in IDEA I get this:

```java
    @jakarta.annotation.Nonnull
    public LombokNullableBuilder value(String value) {
      this.value = value;
      return this;
    }
```

It looks to me that Lombok is working fine, it's just the IDEA plugin is not playing along for some reason. Perhaps need to report this to Jetbrains.

**Comment by mihalyr** [comment]
Reported to JetBrains in https://youtrack.jetbrains.com/issue/IDEA-360058/Lombok-plugin-does-not-add-Nullable-annotations-to-builder-methods

**Comment by internetstaff** [comment]
Thanks, @mihalyr. I confirmed you are correct: it is indeed in the compiled code. Thanks for opening the ticket with Jetbrains!
