### ISSUE TITLE
[BUG] The subclass field does not overwrite the parent class

### ISSUE THREAD

**Issue by qq31715879** [projectlombok/lombok#3769]
```java
package com.kael.test.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;


@Setter
@Getter
@SuperBuilder
@AllArgsConstructor
@NoArgsConstructor
public class TestParentDTO {

    @JsonIgnore
    private String demo;
    private String ddd;
}

package com.kael.test.dto;

import com.jugg.agile.framework.core.util.io.serialize.json.JaJson;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;


@Setter
@Getter
@SuperBuilder
@AllArgsConstructor
@NoArgsConstructor
public class TestChildrenDTO extends TestParentDTO {

    private String demo;

    public static void main(String[] args) {
        TestChildrenDTO testChildrenDTO = new TestChildrenDTO();
        testChildrenDTO.setDemo("ddemo");
        testChildrenDTO.setDdd("ddd");

        System.out.println(JaJson.toString(testChildrenDTO));
    }
}

```

Subclass fields have removed annotations  @JsonIgnore

------------------------------------------
version 1.8.12 can runsuccess
![image](https://github.com/user-attachments/assets/459d0cda-7378-4163-8e0d-94317e7c18ec)

-------------------------------------
but High version failed to run
![image](https://github.com/user-attachments/assets/d8b43935-1b23-4c0d-8bff-da265ded1108)

**Comment by janrieke** [comment]
Things probably changed when Lombok started copying certain annotation to the setter with 1.18.16, including `@JsonIgnore`. Jackson can sometimes be confusing when it comes to detecting which annotations belong to a property, because builds a combination of annotations on the field and its corresponding setters and getters.

With 1.18.12, the annotations was only on the field of the superclass, and Jackson correctly ignores only the field from the parent class. However, once Lombok copies it to the setter, I suspect that Jackson considers this setter method as if it belongs to the property defined in the subclass.

I tend towards "this is a Jackson bug", although you could argue that the setter method is overridden and thus it's the same method. On the other hand, `@JsonIgnore` is not inheritable, so Jackson should not consider it for the subclass property.

From a lombok POV, this is another example why it's a bad idea to copy those Jackson annotations at all.

**Comment by qq31715879** [comment]
@janrieke 
I looked at the class, and in higher versions of Lombok, @ JsonIgnore will be added to the setDemo method of the parent class
I'm not sure if it's a bug with Lombok or Jackson either, but I'm curious why higher versions of Lombok add @ JsonIgnore to the set method

**Comment by qq31715879** [comment]
If @ JsonIgnore must be added to the method, should both the get and set methods be added; However, I personally feel that @ JsonIgnore should not be added to the method. The historical code encountered problems and now I want to upgrade to a higher version of Lombok, but I cannot do it

**Comment by janrieke** [comment]
You should be able to mitigate by adding `@JsonIgnore(false)` to the field in the subclass.

**Comment by qq31715879** [comment]
It's a bit awkward, the historical code is that the parent class defaults to @ JsonIgnore, and some special subclasses need to remove @ JsonIgnore

**Comment by Rawi01** [comment]
You can always add a custom setter without annotation to the parent class.

I agree with @janrieke that this is probably a jackson bug/issue.

**Comment by qq31715879** [comment]
Thank you very much @janrieke

**Comment by janrieke** [comment]
As I just stumbled upon it: According to the [Jackson docs](https://github.com/FasterXML/jackson-annotations?tab=readme-ov-file#improvements-over-typical-java-annotations), this is not a bug, it's a feature.

I'm currently working on #3270, and I'm getting frustrated on this copy-all-those-Jackson-annotations behavior, so I plan on adding a toggle to remove this, maybe even defaulting to "don't copy". I think this would solve several issues people are having.

There are only very limited occasions where the annotations should be copied (having non-standard getters/setters like fluent ones is one of them).
