### ISSUE TITLE
[BUG] Lombok Annotations (Builder, Getter, Setter) Not Working After Restart

### ISSUE THREAD

**Issue by Fayupable** [projectlombok/lombok#3798]
**Describe the bug**
Lombok annotations such as @Getter, @Setter, and @Builder do not function properly in a microservice application after restarting the project. While the annotations are visible in the code, they fail to generate the corresponding methods (getters, setters, etc.).

Additionally, running mvn clean install results in build errors, indicating that Lombok is not processing the code correctly.

**To Reproduce**
1)Add Lombok dependency to the Maven project:
1.18.24 v

2) Use Lombok annotations in a class:
@Getter
@Setter
@Builder
public class Example {
...
}
3) perfom the following steps:
        •	Run mvn clean install.
	•	Restart the application or the IDE.
4)
Check if the generated methods (getName(), setName()) are present.

**Expected behavior**
Lombok should correctly process annotations and generate the required methods without issues. Restarting the application or IDE should not affect Lombok’s functionality.

**Version info (please complete the following information):**
 - Lombok version -> 1.18.24
 - Platform -> IntelliJ IDEA
 -  Maven 3.9.9

**Additional context**
Annotation Processors and ensure “Enable annotation processing” is checked. I did this step. But no matter what I did, lombok annotations are not working

**Comment by Fayupable** [comment]
It doesn't work because the Lombok path is deleted from the IntelliJ IDEA every time I close and open it.

**Comment by janrieke** [comment]
If there would be such a general problem with Lombok we would know it for sure. Thus, your issue must be project-specific, and that makes it impossible to reproduce without the actual project or a minimal reproducible example.

However, there are some things you can try if you cannot share your code:
- Update to the latest Lombok version 1.18.36
-Check for non-star static imports of Lombok-annotated classes. Replace these imports with static star (*) imports.
- Let javac show all compile errors and try to find errors unrelated to Lombok. Sometimes a single javac compiler error can cause a huge cascade of Lombok-related errors because javac won't call Lombok in such cases.
