### ISSUE TITLE
Enhancement: Add @NotEmpty or @NonNull(allowEmpty = false)

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#646]
_Migrated from Google Code (issue 611)_

**Comment by searhiy** [comment]
Hi everyone,

I don't care how you call this feature, but this feature should be :)

On my last project was required to throw an exception if input parameter **null** or **empty**. I couldn't use Hibernate Validator. And what do you think? I used simple if/else statements to reach the goal! 

In core java exist Objects.requireNonNull that throws NullPointerException. But it's not my optional. I had to use my own runtime exception.

Really strange that lombok doesn't have such feature...

For me, I'd like to have not only @NonEmpty annotation but a bit more. Here is useful annotations from hibernate-validator [project](https://github.com/hibernate/hibernate-validator/tree/master/engine/src/main/java/org/hibernate/validator/constraints):

@NotBlank - for strings
@NotEmpty - for collections, etc.
and 
@Pattern from [javax.validation](http://docs.oracle.com/javaee/6/api/javax/validation/constraints/Pattern.html) 

I suppose Pattern annotation will cover everything and it's easy to implement.

I recommend also improve exist annotations with adding the type of exceptions and related message, 
i.e.

@Patter(value="<regex pattern here>", MyException.class, "my custom message here")
or just 
@Patter(value="<regex pattern here>") that will throw IllegalArgumentException by default!

P.S. if it's not a correct issue, please refer me to correct one or I'll create a new one.

- Serhii Kartashov

**Comment by Akceptor** [comment]
Also needed such a feature some time ago. Would really appreciate if it appears

**Comment by mogren** [comment]
Right now we have a lot of this in our code:

```
@Getter
@Builder(buildMethodName = "_buildWithoutValidation")
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(force = true)
public class ServiceRequest {
    
    @NonNull
    private final String alias;
    @NonNull
    private final String key;
    @NonNull
    private final String id;
    
    // optional args
    private final boolean test;
    
    public static class PageContentServiceRequestBuilder {
        public PageContentServiceRequest build() {
            Validate.notEmpty(alias, "Alias cannot be empty");
            Validate.notEmpty(key, "Key cannot be empty");
            Validate.notEmpty(id, "Id cannot be empty");
            return _buildWithoutValidation();
        }
    }
}
```
A @NonEmpty would be great! Would result in something like this instead:

```
@Getter
@Builder
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(force = true)
public class ServiceRequest {
    
    @NonEmpty
    private final String alias;
    @NonEmpty
    private final String key;
    @NonEmpty
    private final String id;
    
    // optional args
    private final boolean test;
}
```

**Comment by searhiy** [comment]
What is expected date for next release then?

**Comment by 7specialgems** [comment]
For me this is the biggest hole in Lombok validation. Add it please and add it soon!

**Comment by rjdthegreat** [comment]
This is exactly what I am looking for: Does someone have a proposed solution?

**Comment by kshav19** [comment]
Any updates on this ??

**Comment by gobozov** [comment]
+1

**Comment by mih-kopylov** [comment]
+1

**Comment by ThommyH** [comment]
+1

**Comment by GlaIZier** [comment]
+1

**Comment by meierval** [comment]
+1

**Comment by p3t** [comment]
Maybe support JSR303 (http://beanvalidation.org/1.0/spec/) in general?

**Comment by odupuy** [comment]
+1

**Comment by jefferyyuan** [comment]
+1, please support this or similar functions. thanks

**Comment by stainii** [comment]
+1!

**Comment by nickdevp** [comment]
+1

**Comment by janrieke** [comment]
Posting those +1's won't help. (Please use reactions to express your opinion.)
@rzwitserloot said in 2013 that this is low priority, and I assume this hasn't changed in the meantime. So I guess the only way having this implemented is to get your hands dirty and create a pull request.
Make sure to clarify all details with the lombok maintainers to avoid having your PR rejected.

**Comment by odrianoaliveira** [comment]
+1

**Comment by longnguyen2306** [comment]
quick comment of remind :)

**Comment by jianchengwang** [comment]
i like this enhancement and hope that will be coming soon.

**Comment by nikolayandr** [comment]
Would be nice to have such annotation @NotBlank

**Comment by a-fatah** [comment]
it would be great if we have this annotation.

**Comment by martin-schaefer** [comment]
I would very much welcome:
- `@NonBlank` for disallowing null, empty or only whitespaces Strings
- `@NonEmpty` for disallowing null or empty Collections

I am using Lombok in many projects but really missing these both annotations

**Comment by marcotama** [comment]
I, too, would love this. I can't seem to get Hibernate's `@NotEmpty` to work on a `Collection`. This annotation would make my life much easier.

**Comment by topr** [comment]
I would appreciate `@NonBlank` and `@NonEmpty` as well. For anyone looking for a workaround with not much boilerplate you may give a try to a _Tiny Type_ pattern. Consider following examples.

Tine type ensuring fail fast on a blank or null value.
```java
import static org.apache.commons.lang3.Validate.notBlank;

@EqualsAndHashCode
public class NonBlankString {
    private final String value;

    public NonBlankString(String value) {
        this.value = notBlank(value);
    }
}
```

Any class at your codebase utilising the above.
```java
@Builder
@RequiredArgsConstructor
public class Foo {
    @NonNull
    private final NonBlankString alias;
    @NonNull
    private final NonBlankString key;
    @NonNull
    private final NonBlankString id;
}
```

Not ideal as it may require some extra mappers/handlers/serializers elsewhere. Those are usually done once as a framework/lib config whilst your model and logic classes may remain concise and blank safe at the same time.

There is yet some hassle with building an object as it would go like `Foo.builder().id(new NonEmptyString("123"))...` which is noisy. However if you let serialise/deserialise data to such tiny types only at the boundaries of your system and later pass them around, you would not face that issue in prod code at all.

In tests, on the other hand, you may extend builder and add convenience overloaded setter methods, something like:

```java
public class TestFooBuilder extends FooBuilder {
    TestFooBuilder id(String value) {
        this.id(new NonBlankString(value));
        return this;
    }
}
```
That's a bit of a pain but pays back quickly when re-used a lot. Also such test builder may become a fixture with pre-set all the necessary values.

Of course an overloaded method may be added straight away in the Lombok's generated builder too if that's the preference, but this gets more noisy in prod code so we're almost back to the former issue.

You may also go more specific with tiny types which actually is their real purpose and (following the example above) create classes like:
- `public class Id extends NonBlankString { /* ... */ }`
- `public class Key extends NonBlankString { /* ... */ }`
- `public class Alias extends NonBlankString { /* ... */ }`

It seems like an overhead at first but you may quickly change your mind when you search for usages of i.e. `Key` where `String` would list you more than half of the codebase :trollface:, or when i.e. it appears that `Id` is not only non-blank but needs to match a certain length or pattern - a change in one place at the `Id` class constructor and voila!

`String` is final but it may get more funky and hasslefree with collections if you are willing to use experimental Lombok feature.
```java
import static org.apache.commons.lang3.Validate.notEmpty

@EqualsAndHashCode
public class NonEmptyList<E> implements List<E> {
    @Delegate
    List<E> source;

    public NonEmptyList(List<E> source) {
        this.source = notEmpty(source);
    }
}
```

Having written all of that, it would be great to have the `@NonEmpty` for collection and `@NonBlank` for string annotations which would cover like 80-90% of use cases :roll_eyes:

**Comment by Avec112** [comment]
I always include Lombok in my projects and I always miss options to use `@NonBlank` and `@NonEmpty` features. `@NonNull` is sometimes used but I still have to check strings for contents as well so I do not really need it since I always end ends up with Apache Commons Lang doing stuff like `StringUtils.isNonBlank(...)` and/or `Validate.notBlank(...)` but most of all I would like Lombok to handle this simple stuff.

**Comment by berndhopp** [comment]
this is a missing feature and should be implemented ASAP.

**Comment by rzwitserloot** [comment]
To give some highlights as to why this is not happening any time soon:

I think most of the folks who are asking for this feature are semantically confused.

Here is an example:

@martin-schaefer wrote:
> @NonBlank for disallowing null, empty or only whitespaces Strings

This doesn't sound right to me. Or at least, I am operating under a semantic understanding of java which makes this statement non-sensical, and therefore the feature a bad idea (in this semantic understanding, such a thing would not be something you'd ever want to have. We might as well offer an annotation that disallowing a string from containing the text "Fruitfly" and "Banana", just as arbitrary and bizarre).

We can debate semantics and whether that understanding is even correct, but unless you can prove that the only correct semantic understanding of java, or at least 90%+ _and rising_ understanding amongst the java community, all are such that this feature makes sense, __we cannot add this feature__. It would be incredibly confusing (as in, they read `@NonBlank` and make assumptions about what that might do, and they would be making the wrong assumptions. We try to avoid that - we strongly prefer features that work like this: Someone sees lombok-annotated code, takes a wild stab in the dark as to what that might mean, and the vast majority of all java programmers doing this would nevertheless guess correctly).

Here's my semantic view:

`null` in java works best if treated exactly like SQL does it: It does __not__ mean blank. It means 'unknown', 'not applicable', 'irrelevant', or 'not yet set'. In other words, in my view, `if (x == null || x.isEmpty())` is __flat out wrong__. These two are not the same thing - `null` means the value simply does not exist, `isEmpty()` means the value does exist, and it is the empty string. If these 2 have the same semantic meaning, then earlier in the chain, somebody messed up. If you meant `""`, then _SEND_ `""`, do not send `null` and write in the spec that this is to be interpreted as identical to the empty string. It is not hard to make empty strings, and it is completely free (I assure you, your VM's heap has an instance of the empty string floating around in there somewhere).

This works well: `null` has the property that most interactions with it result in exceptions. This is __the correct behaviour__ when you treat null as semantically meaning unset/irrelevant/not applicable. Clearly the programmer messed up and is attempting to work with the value of a thing that hasn't been set yet.

With this understanding, `@NonBlank` meaning 'not null, not empty, and no whitespace', is a non sequitur. Sometimes you have external systems (a REST API, and you didn't write it, you're just calling it. Or a file in some format and you're using a library to read it. You did not write this library) which make this error of sending `null` when they ought to be sending an empty string or an empty list. Apply the standard solution anytime you are interacting with external systems with bad APIs: Wrap it if it's really bad, and if not, work around it by adding a cleanup step as close to the interaction as possible. So, when getting data out of the API, clean it up then and there. `if (foo.getName() == null) foo.setName("");` immediately after obtaining `foo`.

Your model (`null` _does_ have semantic meaning) has all sorts of warts and weirdness: You write `if (x == null || x.isEmpty())` everywhere, half of that if branch is usually untestable because you write it out of fear of NPEs and not because you actually know `x` could really be `null` here or not. NPEs are considered 'annoying' because you do not understand why the code doesn't just keep going.

Separate from that, 'only whitespace' is similarly tricky. `.trim()` __does not__ 'trim whitespace'. It trims a specific set of ASCII characters. That's why .strip() now exists (which does trim whitespace). Worldwide definitions on whitespace are therefore now somewhat muddled. I bet if I interview a java coder: "Hey, if I call `.trim()` on a string, and the result of that is a non-zero-length string, clearly that output isn't blank, right?', they would say "yes, of course!", but the answer can actually be "actually, no".

There are probably sane answers to 'define blank'. The point is primarily that there is no broad consensus. That isn't a complete showstopper, but a big issue.

To make a very long story short: Y'all are treating this as a trivial feature. I assure you it is not. It is probably so complicated that the 'value' vs 'cost' analysis will indicate we shouldn't add this feature at all.

Our slate is full, this is not going to happen anytime soon.

**Comment by diliev1996** [comment]
@rzwitserloot what about adding @NotEmpty

**Comment by rzwitserloot** [comment]
> @rzwitserloot what about adding @notempty

Just as complicated. It still suffers from the notion that most would presumably assume that this means 'non empty string' when applied to strings, but may also assume that it strips spaces. For lists and the like, how would you like to define this? We can't resolve, we have no idea if `JanesAwesomeList` has an `isEmpty` method or not. At best we could say: When you use this, we call `.isEmpty()` on the thing and if it doesn't exist, we still do it - thus producing a compiler error.

However, I bet half the java community thinks it is utterly obvious, and therefore won't even consider the idea that it _doesnt_, that this also checks for `null` and will just fail on null as normal (treating it as identical to empty), and the other thinks the opposite and is equally convinced their way is the only sane way.

But we can't cater to both of them, so no matter what we do, we tick off half the java community. This kills the issue tracker, and therefore, no can do.

**Comment by rzwitserloot** [comment]
> or that this is a code smell and we probably should rethink the code... then ... we don't care and just want something to reduce lines.

If you're looking for a tool that papers over bizarre code we just plain cannot deliver, because legacy bizarro code from the ancient pits of the past isn't consistently awful. I have no qualms about giving it to you - but what you want results in 85 other hugadams-esque java programmers filing bugs that the stuff we produced to handle your case _seems_ to apply also to their weird legacy morass but doesn't actually work right, and they file bugs.

Until we have a full inventory of all the myriad ways folks write bizarro / legacy / weird code, and can therefore try to find a line that caters to most and at leats doesn't confuse the remainer - I'm game to add such things.

But I see no way to produce such a full inventory. I'm sure you can tell me "Just add this feature and all my problems will be solved", but that's just _your_ problems. What about everyone else's?

**Comment by MattMCloudy** [comment]
@rzwitserloot 

I understand this is one of these long-term issues that's frustrating to keep discussing, so sorry to revive the thread on this. It's apparent from your previous comment that your primary concern is landing on a way to perform this check that best matches the `null` semantic in Java. I'll say that for my team, we're almost always using lombok in conjunction with Apache StringUtils (as well as set, map, list, etc.). Would it be a more reasonable ask to have a lombok extension of Apache that just acts as syntactic sugar for the bindings that already exists in the service's dependency closure? In that case (or something like it) lombok wouldn't be responsible for making decisions on the "isBlank" / "isEmpty" checks itself, and service owners would just need to confirm that the Apache implementation covers whatever cases they want to check.

**Comment by rajmondx** [comment]
**Workaround for spring users:**

1. **Lombok **
   Use Lombok annotations to reduce boilerplate code in entity/domain models:
   - `@Data` (or `@Getter`, `@Setter` for more control)
   - `@NoArgsConstructor` for a no-argument constructor
   - `@AllArgsConstructor` for an all-argument constructor
   - `@NonNull` for mandatory fields
   - `@Builder` for easy object construction

   This setup creates clean, concise domain models.

2. **@Validation**
   Use validation annotations to ensure client data integrity:
   - `@Valid` for validating nested objects
   - `@NotNull` for mandatory fields
   - `@NotEmpty` for non-empty collections or strings
   - `@Size(max = 10)` to restrict field length

   Place these annotations on DTOs or entities to enforce constraints before processing.
   
   I dont like it neither but thats my current workaround. Using it basically for DTOs and DAOs only
