### ISSUE TITLE
Constructor annotations ignore annotations on fields

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#745]
_Migrated from Google Code (issue 710)_

**Comment by ewirch** [comment]
+1 (I wish GitHub would have a vote feature)

**Comment by davinkevin** [comment]
And qualifier for dependency injection.

**Comment by ohrytsenko** [comment]
+1

**Comment by lc-nyovchev** [comment]
+1

**Comment by bajaj** [comment]
+1

**Comment by rodolfocal** [comment]
+1

**Comment by EmkaMk** [comment]
+1 please :)

**Comment by mhaefele** [comment]
+1

**Comment by tomaszc** [comment]
+1

**Comment by myoffe** [comment]
I'm experiencing this when trying to inject a Spring `@Value` like so:

```
@Component
@RequiredArgsConstructor
public class MySpringComponent {
    @Value("${config.param.value}")
    private final String someConfigParam;
}
```

When I `bootRun` the app, Spring complains that it cannot instantiate a bean of type `String`.
I expect Lombok to generate a constructor that includes this annotation.

Thanks!

**Comment by lc-nyovchev** [comment]
hey @myoffe 

We have been using the same approach successfully on lombok 1.16.20.  I guess you were inspired by this article, or one of the earlier: 

http://www.baeldung.com/spring-injection-lombok
https://spring.io/blog/2015/11/29/how-not-to-hate-spring-in-2016

However, there are two things to mention your approach:

- putting a @Value in your @Component is not a good practice

you should replace it with stuff like:

```
@Component
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
public class MySpringComponent {
       @NonNull private final Config someConfig;
} 
```

where your config is like following:

```
@Configuration
@RequiredArgsConstructor
public class Config {
         @Value("${config.param.value}") private final String someConfigParam;
}
```

However, here you'd have the same problem. The reason behind it is that what you want is:

@Configuration
public class Config {
          
          private final String someConfigParam;

          public Config(@Value("${config.param.value}" String someConfigParam){
               this.someConfigParam = someConfigParam;
          }
}

but what you actually end up with is:

```

@Configuration
public class Config {
          
         @Value("${config.param.value}") private final String someConfigParam;

          public Config(String someConfigParam){ //Spring has no idea how to wire this property now 
               this.someConfigParam = someConfigParam;
          }
}
```

The reason why it is not so simple to fix is that, as you can see:

`@Target({ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER, ElementType.ANNOTATION_TYPE})`

The @Value annotation by Spring is rather permissive in terms where it can be placed. In other cases, however, an annotation that is a Field annotation might not be having the Parameter or Method target, so it would be impossible.

My suggestion to the lombok maintainers is to identify places where it is possible (and desirable to do so)

- @NonNull is nice to be both on a field and copied on a constructor
- @org.springframework.beans.factory.annotation.Value is also nice to be both on a field an be copied on a constructor with a RequiredArgsConstructor

but sometimes, there are annotations which either can't be copied onto the constructor as they are FIELD only annotations, or we simply don't want to do that. So I guess this requires some consideration on the API to be exposed so we have some fine tuning to turn on or off.

**Comment by myoffe** [comment]
Hey @lc-nyovchev, thanks for your comment!
I agree that the separate configuration service is the right approach.
Also, thinking about it more, I understand that it's not trivial at all to assume that annotations will go into the constructor.

By the way: if you have a Spring bean like this:
```
@Component
@RequiredArgsConstructor
public class MyBean {}
```
and you only have one constructor (the generated one), you don't need to add the `onConstructor = @__(@Autowired))` part, Spring will automatically use that constructor for injecting.

**Comment by Felk** [comment]
This would also be useful for Jackson-compatible immutable DTOs that have all-final fields annotated with `@JsonProperty("fieldName")`, where the constructor parameters also need the annotation

**Comment by rspilker** [comment]
In the next release, it is possible to configure what annotation types should be copied from the field to the parameters. It is already available in the [edge release](https://projectlombok.org/download-edge). Feedback is welcome.

**Comment by benjaminjbachman** [comment]
Works great!  This is going to make guice + lombok very slick.

One issue I'm having is figuring out how to add an inner class annotation to lombok.config?  I've tried mypackage.MyClass$MyInnerAnnotation but no dice?

**Comment by Maaartinus** [comment]
@benjaminjbachman 
> I've tried mypackage.MyClass$MyInnerAnnotation but no dice?

Haven't you tried `mypackage.MyClass.MyInnerAnnotation`? No idea, if it works, but that's what I'd try.

**Comment by LukaszTheProgrammer** [comment]
@rspilker can you give an example how to achieve that in the latest edge release?
Assuming I have a class like this:
@AllArgsConstructor
class A{
 @Qualifier
private final Pojo pojo;
}
what is the configuration I should make to have @Qualifier on the generated constructor's parameter.

**Comment by benjaminjbachman** [comment]
> @benjaminjbachman
> 
> > I've tried mypackage.MyClass$MyInnerAnnotation but no dice?
> 
> Haven't you tried `mypackage.MyClass.MyInnerAnnotation`? No idea, if it works, but that's what I'd try.

I did try that too; did not work.

**Comment by benjaminjbachman** [comment]
> @rspilker can you give an example how to achieve that in the latest edge release?
> Assuming I have a class like this:
> @AllArgsConstructor
> class A{
> @qualifier
> 
> what is the configuration I should make to have @qualifier on the generated constructor's parameter.

Make a lombok.config file with 

`lombok.copyableAnnotations += mypackage.qualifier` where mypackage.qualifier is the full class name.

**Comment by LukaszTheProgrammer** [comment]
@benjaminjbachman Thanks it works.

**Comment by benjaminjbachman** [comment]
> One issue I'm having is figuring out how to add an inner class annotation to lombok.config? I've tried mypackage.MyClass$MyInnerAnnotation but no dice?

@rspilker any thoughts on this issue?  is this a bug or am I doing the config wrong?

**Comment by lc-nyovchev** [comment]
I suggest closing the ticket as it is possible now to achieve everything we ever wanted:

https://ath3nd.wordpress.com/2018/12/13/spring-lombok-or-injection-just-became-a-bit-easier-part-2-of-2/

Thanks a bunch for the great implementation @rspilker !

**Comment by zachofalltrades** [comment]
@rspilker 

I only recently discovered `lombok.copyableAnnotations` it is **_almost_** perfect for what I need.

Like many people, I do a lot of Spring Boot development, and I have come agree with a lot of purists who insist that field level injection is bad, and all services should use constructor injection.

When I am writing a service class that needs some beans, I just declare them all private final, and add the `@RequiredArgsConstructor` annotation at the top of the class and everything works **great**.

But when my service class needs just a simple configuration property, I have to go back to creating the constructor that sets all of the beans and use Spring's `@Value` annotation in order to resolve the config property. 

Now that I have discovered the feature discussed in this thread, I can configure lombok with 
```
lombok.addLombokGeneratedAnnotation = true
lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Value
``` 
which allows me to do this:
```
@Service
@Slf4j
@RequiredArgsConstructor
class MyService {
    private final SomeThing thing;
    private final OtherComponent other;
    @Value("${my.config.key}"
    private final String myConfigVal;
}
```
and then I get the generated constructor with the `@Value` annotation exactly the way I need it. 
```
@Service
class MyService {
    @Generated
    private static final Logger log = LoggerFactory.getLogger(MyService.class);
    private final SomeThing thing;
    private final OtherComponent other;
    @Value("${my.config.key}"
    private final String myConfigVal;

    @Generated
    public MyService (final SomeThing thing, final OtherComponent other, @Value("${my.config.key}" final String myConfigVal) {
      this.thing = thing;
      this.other = other;
      this.myConfigVal = myConfigVal;
    }
}
```
**But** the `@Value` annotation _remains on the field_ itself  (making for an ambiguous IoC setup)
I disagree with @lc-nyovchev where he indicates https://github.com/projectlombok/lombok/issues/745#issuecomment-357714897 that would be desirable to have the annotation on the field AND on the constructor parameter.

And unfortunately, the `onConstructor` experimental feature does not address this use case, because it applies the requested annotation to the whole constructor method. It might be easier to satisfy this use case with a new and specific lombok annotation that could be applied to a field, and would designate annotation(s) to be moved to constructor arguments.

**Comment by rzwitserloot** [comment]
@zachofalltrades The problem now is that we end up in a combinatory explosion of options.

It's like a noodleshop ordering menu:

* Would you like us to remove the annotation from the field, or keep it there? Trivial example for removal: Your case, any annotation whose `@Target` list doesn't include `FIELD`. 3 choices: No, Yes - but only if lombok generates anything, and Aggressively Yes - lombok should delete this annotation even if lombok ends up not generating anything.
* Would you like us to copy the annotation to the setter parameter (likely cases: Any annotation whose targets include TYPE_USE or PARAMETER but not METHOD), or copy it to the setter method itself (likely cases: Any annotation whose targets include METHOD), or not copy it at all to setters? 3 choices.
* Would you like us to copy the annotation to the relevant argument to any generated constructors, or not? 2 choices.
* Would you like us to copy the annotation to generated getters, or not? 2 choices.
* Would you like us to copy the annotation to the generated wither's parameter, or to the generated wither itself (on the method), or to nothing. Let's assume that _if_ you want copying to occur in the first place, that you then want the same choice (between: Don't / to the param / to the method) as for the setter, so, 2 choices.
* 
No 'path' of choices is on its face idiotic, therefore nothing can be eliminated, thus we simply multiply: 3*3*2*2*2 is __72 different configurations__.

How in the blazes do we make that accessible to lombok users? The only feasible option appears to be to actually list out all these options, and thus end up with either in lombok.config:

```
lombok.copyableAnnotations = com.foo.MyAnnotation(mode = ON_PARAM, setters = true, withers = true, getters = true, constructorParams = false, deleteFromField = AGGRESSIVE)
```

Or something like:

```
@AnnotationCopyingBehaviour(target = com.foo.MyAnnotation.class, mode = CopyingMode.ON_PARAM, toSetters = true, toWithers = true, toGetters = true, toConstructorParams = false, deleteMode = DeleteMode.AGGRESSIVE)
```

Which is a ton of text, and thus rather awkward for a boilerplate busting tool, and in any case can you imagine the documentation for this feature? It'd be a joke.

Hence __we just cannot do this__, or at least, I'm making a decision here, and we won't. I get your current needs, but once you take the millions of lombok user's individual needs, toss em in a bag, and have a look and see how you can cater to all of them, hopefully you see why I have to ignore this.

Our solution is very different: We cater to the community. As in, we hardcode into lombok all commonly used annotations and register in lombok source code what the right behaviours are. And yes, that system may need some extension to really really support all 72 cases.

We keep the current `copyableAnnotations` system but its intent is effectively for TYPE_USE style things like `@NonNull` where the idea is that if you want it copied at all, it's always to the param, and to spam it (copy it everywhere relevant and keep it on the field as well).

This gives a lot of advantages:

* Lombok just works out of the box for everything we hardcoded.
* For the stuff we didn't hardcode, I'm pretty sure the top hit in that list of 72, by a large margin, is 'copy to setter param, getter method, wither param, and constructor param, and do not delete from field', and we do cater to this via `copyableAnnotations`.
* We do not need to document the combinatory explosion. Just explaining all this is on its own a herculean task, and would be quite a mismatch: We'd be tossing 5 pages worth of docs at something that the user probably thought was really simple. In my experience, the messenger is shot _all the time_ in such scenarios. Lombok will be blamed for making something simple needlessly complicated (erroneously; it's not simple, but many folks don't know that and don't want to accept it, because in their world, most of those 72 cases seem silly).
* We do not need to build half of a programming language in `lombok.config` to let you specify which of the combinatory explosion you want.

Hence, that's the plan.

It does mean we need to make it simpler to send Pull Requests. This is on its own also quite complicated, as we don't know every library out there. Given we don't have infinite time to go check 'your work', and I think maven central and other projects have thoroughly showed that just blanket accepting all contributions leads to a crap ecosystem, how do we 'judge' whether a PR correctly identified which of the 72 is right? How do we 'judge' a conflict where we get 2 issues that indicate conflicting answers?

To solve _that_, I think we instigate the following process:

* If you want the lombok hardcoded list to include your annotation, it _must_ be for a maven-hosted dependency, and open source (I'm not avidly anti-closed-source or anything, but there's simply no way for us to judge or test closed source stuff), __and the PR must be sent or endorsed by the project owners__.
* Hence, you'd have to ask the project owners to create or at least endorse your PR, otherwise we simply can't accept it.
* This absolves us of becoming arbiters. We can just tell anybody who feels the setting is wrong: Well, the project owners disagree with you, so get lost. Or rather, talk to the project owners and convince them to tell us that they messed up and a different setting is now required. We can then also aggressively redirect everybody to the project owners to go yell at them for breaking backwards compatibility (as any change in which of the 72 is, naturally, backwards incompatible). It also significantly increases the odds that the first take ends up being the right one.

I expect few takers on this, so I'm not rating the priority of making it easy to write those PRs as particularly highly. Hence, I'm just closing this. Maybe we'll get around to it someday. But a well written take (so, includes tests and documentation, and updates all relevant parts of lombok, both ecj and javac side, to use a single frameworky thing to navigate through that sea of 72 choices), if sent as a PR, would be accepted.

**Comment by zachofalltrades** [comment]
@rzwitserloot you have given a wonderful explanation of the complexity that would be involved in making `lombok.copyableAnnotations` fully configurable. 

Thank you. 

I am not so foolish as to think that it would have been easy to set up configurable behavior for `copyableAnnotations`, and I do not begrudge your decision to shield the community from something that could easily have led into a quagmire. 

The very last thing I said was that "It might be easier to satisfy this use case with a new and specific lombok annotation that could be applied to a field, and would designate annotation(s) to be moved to constructor arguments." I will try to do some homework on the subject and see if I can come up with a more specific proposal in a new feature request (or PR) -- or I will simply resign myself to being happy about the volume of boilerplate code that lombok has already saved me from writing over the years and find some other new ways to avoid work.

**Comment by rzwitserloot** [comment]
@zachofalltrades Thanks for understanding! – one problem with an annotation that triggers: "Move it": Don't you kinda need 72 annotations then? Or is specifically 'move to constructor' a very common case? If you put it in light of a specific dependency, we can put it in the `lombok.extern` package and this solves a ton of problems. Also, it feels like a choice applies to a specific annotation, and not neccessarily to all of them. However, you can't annotate an annotation. You then get to something fairly ugly:

```java
@MoveToConstructor(annotations = YourAnnotation.class) @YourAnnotation String foo;
```

Possible, but, sheesh.
