### ISSUE TITLE
Delombok a single annotation

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#746]
_Migrated from Google Code (issue 711)_

**Comment by timtebeek** [comment]
@rzwitserloot  Would you ever reconsider this position? We're coming across an issue where other tools do not play well with Lombok, and where it would be nice to retain the majority of what Lombok offers, but remove a single feature. ([In this case val](https://github.com/openrewrite/rewrite/issues/1297)).

There are other use cases as well such as retroactively banning `@SneakyThrows` from the organization, which would benefit from a `feature` argument to [Delombok.CmdArgs](https://github.com/projectlombok/lombok/blob/master/src/delombok/lombok/delombok/Delombok.java#L111), possibly combined with an `inplace` argument to update the source rather than a target.

I understand there's already so much to work on, but I really think it would underwrite the notion that Lombok is safe to use, and easy to selectively retire features in the future if need arises.

**Comment by rzwitserloot** [comment]
`val` migration is certainly useful, yes. But I think we need to do something else for that - if delombok makes modifications it might various parts of your file a little bit (not in a syntactically relevant way, of course).

For `val` specifically we could write something that leaves everything bit-for-bit intact, replacing _just_ `val`.

Or possibly even simpler, just replace `val` with `final var` and be done with it, which is probably the simplest thing to do here (and if you want to move away from `val` but stick with JDK8, maybe we just say you can't do that).

A 'dumb' `sed` script can do it, more or less, but it'd be nice if only specifically `lombok.val` usage is replaced and not any mention of `val` anywhere in a java file. That's not quite safe.

> There are other use cases as well such as retroactively banning @SneakyThrows from the organization

That sounds like a mistake. Nothing about why `@ST` has been introduced changed.

> possibly combined with an inplace argument to update the source rather than a target.

Boy, the scope creep, I can _smell_ it from here.

A `val` replacement script, that makes sense to me. The rest not so much.

**Comment by rzwitserloot** [comment]
Well, the `sed` thing is hard to do correctly, in the sense that you don't want `String x = "Please select a different val"` to be turned into `String x = "Please select a different final var"`, but writing a sed script to do it correctly is tricky, especially considering that `int val = 5;` is legal java and definitely should not become `int final var = 5;`.

I think a separate issue is in order, specifically for a `java -jar lombok.jar valToVar` command (Possibly it makes more sense to make this a 'mode' of the delombok tool instead, we'll think about it).

**Comment by rzwitserloot** [comment]
Go ahead :)

**Comment by timtebeek** [comment]
Perfect, thanks; details here: https://github.com/projectlombok/lombok/issues/3207
