### ISSUE TITLE
generate hasFOO() for boolean fields named 'hasFOO' instead of 'isHasFOO'

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#77]
_Migrated from Google Code (issue 4)_

**Comment by Ghedeon** [comment]
Sorry, I see that it's an old thread, but do I miss something or was it reverted? Because it generates `isHasFoo()` for the field named `hasFoo` in `v1.16.16`.

**Comment by Maaartinus** [comment]
@Ghedeon IIRC this has indeed been reverted. It makes the names sound better, but it's another "prefix-shedding", incompatible with javabeans and not very systematic. There (at least) following possibilities:
- javabeans compatible
- no prefix
- always get/set (never "is")

**Comment by bmmpt** [comment]
Why not give the developer the ability so set the exact getter/setter name they what to use?

For instance I have a Boolean getter I would like to call canAdd... rather than isAdd or hadAdd.

Something like the following would be nice:

@Getter(name="canAdd")
@Setter(name="setCanAdd")
private Boolean thisNameDoesNotMatter;
